# Generated by Django 5.1.2 on 2025-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupply",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("litros", "Litros"),
                    ("mililitros", "Mililitros"),
                    ("galones", "Galones"),
                    ("kilos", "Kilos"),
                    ("gramos", "Gramos"),
                    ("toneladas", "Toneladas"),
                    ("libras", "Libras"),
                    ("onzas", "Onzas"),
                    ("bultos", "Bultos"),
                    ("sacos", "Sacos"),
                    ("unidades", "Unidades"),
                    ("metros", "Metros"),
                    ("centímetros", "Centímetros"),
                    ("milímetros", "Milímetros"),
                    ("hectáreas", "Hectáreas"),
                    ("otros", "Otros"),
                ],
                default="unidades",
                max_length=20,
                null=True,
                verbose_name="Unidad de medida",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupply",
            name="unit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Cantidad de unidad de medida",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupply",
            name="unit_custom",
            field=models.CharField(
                blank=True,
                help_text="Especifique la unidad si seleccionó 'Otros'.",
                max_length=50,
                null=True,
                verbose_name="Unidad personalizada",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("litros", "Litros"),
                    ("mililitros", "Mililitros"),
                    ("galones", "Galones"),
                    ("kilos", "Kilos"),
                    ("gramos", "Gramos"),
                    ("toneladas", "Toneladas"),
                    ("libras", "Libras"),
                    ("onzas", "Onzas"),
                    ("bultos", "Bultos"),
                    ("sacos", "Sacos"),
                    ("unidades", "Unidades"),
                    ("metros", "Metros"),
                    ("centímetros", "Centímetros"),
                    ("milímetros", "Milímetros"),
                    ("hectáreas", "Hectáreas"),
                    ("otros", "Otros"),
                ],
                default="unidades",
                max_length=20,
                null=True,
                verbose_name="Unidad de medida",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="unit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Cantidad de unidad de medida",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="unit_custom",
            field=models.CharField(
                blank=True,
                help_text="Especifique la unidad si seleccionó 'Otros'.",
                max_length=50,
                null=True,
                verbose_name="Unidad personalizada",
            ),
        ),
    ]
