# Generated by Django 5.1.2 on 2025-07-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_historicalsupply_unit_historicalsupply_unit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmachinery',
            old_name='serial',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='machinery',
            old_name='serial',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='historicalmachinery',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='historicalmachinery',
            name='type_of_machinery',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='type_of_machinery',
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.warehouse', verbose_name='Almacén'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machinery_images/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery', to='inventario.warehouse', verbose_name='Almacén'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
