# Generated by Django 5.1.2 on 2025-07-14 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_serial_historicalmachinery_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmachinery',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor actual'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Último mantenimiento'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación física'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de compra'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable actual'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('en_reparacion', 'En reparación'), ('fuera_servicio', 'Fuera de servicio')], default='nuevo', max_length=30, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalmachinery',
            name='usage_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de uso'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor actual'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Último mantenimiento'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación física'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de compra'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable actual'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('en_reparacion', 'En reparación'), ('fuera_servicio', 'Fuera de servicio')], default='nuevo', max_length=30, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='usage_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de uso'),
        ),
    ]
