# Generated by Django 5.1.2 on 2025-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_historicalmachinery_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT/RUT'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT/RUT'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto'),
        ),
    ]
