# Generated by Django 5.1.2 on 2025-07-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0006_person_company_image_historicalcompany_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventorymovement',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='historicalinventorymovement',
            name='origin_warehouse',
        ),
        migrations.RemoveField(
            model_name='historicalinventorymovement',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='origin_warehouse',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='supply',
        ),
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de activo'),
        ),
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='destination_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación/Almacén destino'),
        ),
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Documento adjunto'),
        ),
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de activo'),
        ),
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='origin_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación/Almacén origen'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de activo'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='destination_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación/Almacén destino'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='movements/', verbose_name='Documento adjunto'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de activo'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='origin_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación/Almacén origen'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], max_length=15, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], max_length=15, verbose_name='Tipo de movimiento'),
        ),
    ]
