# Generated by Django 5.1.2 on 2025-07-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0007_remove_historicalinventorymovement_destination_warehouse_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupply",
            name="attachments",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Adjuntos"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupply",
            name="image",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Imagen"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupply",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notas"),
        ),
        migrations.AddField(
            model_name="supply",
            name="attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="supply_attachments/",
                verbose_name="Adjuntos",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="supply_images/", verbose_name="Imagen"
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notas"),
        ),
        migrations.AddField(
            model_name="supply",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="supplies",
                to="inventario.supplier",
                verbose_name="Proveedores",
            ),
        ),
    ]
