# Generated by Django 5.1.2 on 2026-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0008_historicalsupply_attachments_historicalsupply_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalcategory",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalinventorymovement",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalmachinery",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubcategory",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplier",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupply",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalwarehouse",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="machinery",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
    ]
