# Generated by Django 5.0.1 on 2026-08-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0009_category_tenant_id_company_tenant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupply",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                help_text="Por debajo de esta cantidad se genera alerta.",
                max_digits=12,
                verbose_name="Stock minimo",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                help_text="Por debajo de esta cantidad se genera alerta.",
                max_digits=12,
                verbose_name="Stock minimo",
            ),
        ),
    ]
