# Generated by Django 5.1.2 on 2026-08-20 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0010_move_labor_input"),
        ("inventario", "0010_add_minimum_stock_to_supply"),
        ("labores", "0005_add_maquinaria_to_labor"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinventorymovement",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crop.crop",
                verbose_name="Cultivo destino",
            ),
        ),
        migrations.AddField(
            model_name="historicalinventorymovement",
            name="labor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="labores.labor",
                verbose_name="Labor destino",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="crop.crop",
                verbose_name="Cultivo destino",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="labor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="labores.labor",
                verbose_name="Labor destino",
            ),
        ),
    ]
