# Generated by Django 5.1.2 on 2026-08-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0011_historicalinventorymovement_crop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwarehouse",
            name="capacity",
            field=models.CharField(
                blank=True,
                help_text="Ej: 200 m³, 50 toneladas",
                max_length=100,
                null=True,
                verbose_name="Capacidad",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="capacity",
            field=models.CharField(
                blank=True,
                help_text="Ej: 200 m³, 50 toneladas",
                max_length=100,
                null=True,
                verbose_name="Capacidad",
            ),
        ),
    ]
