# Generated by Django 5.1.2 on 2025-07-23 15:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRHH', '0003_initial'),
        ('crop', '0001_initial'),
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de labor')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de labor',
                'verbose_name_plural': 'Tipos de labor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la labor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_realizada', models.DateField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('duracion', models.FloatField(blank=True, null=True, verbose_name='Duración (horas)')),
                ('costo_total', models.FloatField(blank=True, null=True, verbose_name='Costo total')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cultivo_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_principales', to='crop.crop', verbose_name='Cultivo principal')),
                ('cultivos', models.ManyToManyField(blank=True, related_name='labores', to='crop.crop', verbose_name='Cultivos involucrados')),
                ('parcelas', models.ManyToManyField(blank=True, related_name='labores', to='parcels.parcel', verbose_name='Parcelas involucradas')),
                ('responsables', models.ManyToManyField(blank=True, related_name='labores_asignadas', to='RRHH.employee', verbose_name='Responsables')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labores.labortype', verbose_name='Tipo de labor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLaborPhoto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(max_length=100, verbose_name='Foto de labor')),
                ('date', models.DateField(verbose_name='Fecha de la foto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(blank=True, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('labor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='labores.labor')),
            ],
            options={
                'verbose_name': 'historical Foto de labor',
                'verbose_name_plural': 'historical Fotos de labores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LaborPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='labor_photos/', verbose_name='Foto de labor')),
                ('date', models.DateField(verbose_name='Fecha de la foto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='labores.labor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Foto de labor',
                'verbose_name_plural': 'Fotos de labores',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLabor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la labor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_realizada', models.DateField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('duracion', models.FloatField(blank=True, null=True, verbose_name='Duración (horas)')),
                ('costo_total', models.FloatField(blank=True, null=True, verbose_name='Costo total')),
                ('creado_en', models.DateTimeField(blank=True, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cultivo_principal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crop.crop', verbose_name='Cultivo principal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='labores.labortype', verbose_name='Tipo de labor')),
            ],
            options={
                'verbose_name': 'historical labor',
                'verbose_name_plural': 'historical labors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
