# Generated by Django 5.1.2 on 2026-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabor",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="labor",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="labortype",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
    ]
