# Generated by Django 5.0.1 on 2026-08-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labores", "0002_historicallabor_tenant_id_labor_tenant_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborPhase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre de la fase"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En progreso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de finalizacion"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas / Inconvenientes"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "labor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fases",
                        to="labores.labor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fase de labor",
                "verbose_name_plural": "Fases de labor",
                "ordering": ["orden"],
            },
        ),
    ]
