# Generated by Django 5.0.1 on 2026-08-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0010_add_minimum_stock_to_supply"),
        ("labores", "0004_move_labor_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="labor",
            name="maquinaria",
            field=models.ManyToManyField(
                blank=True,
                related_name="labores",
                to="inventario.machinery",
                verbose_name="Maquinaria utilizada",
            ),
        ),
        migrations.AlterField(
            model_name="historicallabor",
            name="fecha_realizada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de realizacion"
            ),
        ),
        migrations.AlterField(
            model_name="labor",
            name="fecha_realizada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de realizacion"
            ),
        ),
    ]
