# Generated by Django 5.0.1 on 2026-02-05 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_agrotech', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Explorador'), ('basic', 'Agricultor'), ('pro', 'Empresarial'), ('enterprise', 'Corporativo')], db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del plan')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price_cop', models.DecimalField(decimal_places=2, default=0, help_text='Precio mensual en pesos colombianos', max_digits=12, verbose_name='Precio en COP')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, help_text='Precio mensual en dólares', max_digits=10, verbose_name='Precio en USD')),
                ('frequency', models.IntegerField(choices=[(1, 'Mensual'), (3, 'Trimestral'), (12, 'Anual')], default=1, help_text='En meses: 1=Mensual, 3=Trimestral, 12=Anual', verbose_name='Frecuencia de cobro')),
                ('limits', models.JSONField(default=dict, help_text='Ejemplo: {"hectares": 300, "users": 3, "eosda_requests": 100, "parcels": 10, "storage_mb": 500}', verbose_name='Límites del plan')),
                ('features_included', models.JSONField(default=list, help_text='Lista de features disponibles en este plan', verbose_name='Características incluidas')),
                ('features_excluded', models.JSONField(default=list, help_text='Lista de features NO disponibles (para mostrar en comparación)', verbose_name='Características excluidas')),
                ('mercadopago_plan_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del plan en MercadoPago')),
                ('paddle_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del producto en Paddle')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del precio en Stripe (futuro)')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar para ocultar de la lista de planes disponibles', verbose_name='Plan activo')),
                ('is_custom', models.BooleanField(default=False, help_text='True para planes Enterprise con pricing custom', verbose_name='Plan personalizado')),
                ('trial_days', models.IntegerField(default=14, help_text='Período de trial gratuito en días', verbose_name='Días de prueba')),
                ('sort_order', models.IntegerField(default=0, help_text='Para ordenar planes en la UI (menor primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['sort_order', 'tier'],
                'indexes': [models.Index(fields=['tier', 'is_active'], name='billing_pla_tier_fdafe0_idx'), models.Index(fields=['sort_order'], name='billing_pla_sort_or_55d056_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('payment_gateway', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('paddle', 'Paddle'), ('stripe', 'Stripe'), ('manual', 'Manual')], default='mercadopago', help_text='Gateway usado para procesar pagos', max_length=50, verbose_name='Pasarela de pago')),
                ('external_subscription_id', models.CharField(blank=True, help_text='ID de la suscripción en la pasarela de pago', max_length=200, null=True, verbose_name='ID externo')),
                ('status', models.CharField(choices=[('trialing', 'En período de prueba'), ('active', 'Activa'), ('past_due', 'Pago vencido'), ('canceled', 'Cancelada'), ('paused', 'Pausada'), ('expired', 'Expirada')], db_index=True, default='trialing', max_length=20, verbose_name='Estado')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=10, verbose_name='Ciclo de facturación')),
                ('current_period_start', models.DateTimeField(verbose_name='Inicio período actual')),
                ('current_period_end', models.DateTimeField(verbose_name='Fin período actual')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin del trial')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Si True, no se renovará automáticamente', verbose_name='Cancelar al fin del período')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación automática')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional de la suscripción', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='Plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='base_agrotech.client', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='IVA 19% en Colombia', max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Pendiente'), ('paid', 'Pagada'), ('void', 'Anulada'), ('uncollectible', 'Incobrable')], db_index=True, default='draft', max_length=20, verbose_name='Estado')),
                ('invoice_date', models.DateField(verbose_name='Fecha de factura')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de pago en MercadoPago')),
                ('paddle_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de pago en Paddle')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de factura en Stripe')),
                ('dian_invoice_number', models.CharField(blank=True, help_text='Número de factura electrónica DIAN', max_length=100, null=True, verbose_name='Número DIAN')),
                ('dian_pdf_url', models.URLField(blank=True, null=True, verbose_name='URL PDF DIAN')),
                ('dian_xml_url', models.URLField(blank=True, null=True, verbose_name='URL XML DIAN')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Archivo PDF')),
                ('line_items', models.JSONField(default=list, help_text='Ejemplo: [{"description": "Plan Pro", "quantity": 1, "amount": 149000}]', verbose_name='Líneas de factura')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='base_agrotech.client', verbose_name='Tenant')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscription.created', 'Suscripción creada'), ('subscription.updated', 'Suscripción actualizada'), ('subscription.canceled', 'Suscripción cancelada'), ('subscription.renewed', 'Suscripción renovada'), ('invoice.created', 'Factura creada'), ('invoice.paid', 'Factura pagada'), ('invoice.payment_failed', 'Pago fallido'), ('plan.upgraded', 'Plan mejorado'), ('plan.downgraded', 'Plan reducido'), ('usage.exceeded', 'Límite excedido'), ('trial.started', 'Trial iniciado'), ('trial.ended', 'Trial finalizado')], db_index=True, max_length=50, verbose_name='Tipo de evento')),
                ('event_data', models.JSONField(default=dict, verbose_name='Datos del evento')),
                ('external_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID externo del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='base_agrotech.client', verbose_name='Tenant')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Evento de Facturación',
                'verbose_name_plural': 'Eventos de Facturación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('hectares_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hectáreas usadas')),
                ('eosda_requests', models.IntegerField(default=0, verbose_name='Peticiones EOSDA')),
                ('users_count', models.IntegerField(default=0, verbose_name='Cantidad de usuarios')),
                ('parcels_count', models.IntegerField(default=0, verbose_name='Cantidad de parcelas')),
                ('storage_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Almacenamiento en MB')),
                ('hectares_overage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hectáreas en exceso')),
                ('eosda_requests_overage', models.IntegerField(default=0, verbose_name='Peticiones EOSDA en exceso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.subscription', verbose_name='Suscripción')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='base_agrotech.client', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Métrica de Uso',
                'verbose_name_plural': 'Métricas de Uso',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_684a21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant'], name='billing_sub_tenant__7e6f87_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['payment_gateway', 'external_subscription_id'], name='billing_sub_payment_4d2293_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='billing_inv_tenant__f82d44_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='billing_inv_invoice_2a056e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['tenant', 'event_type'], name='billing_bil_tenant__4ea60e_idx'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['created_at'], name='billing_bil_created_53ac4b_idx'),
        ),
        migrations.AddIndex(
            model_name='usagemetrics',
            index=models.Index(fields=['tenant', 'year', 'month'], name='billing_usa_tenant__d7a669_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagemetrics',
            unique_together={('tenant', 'year', 'month')},
        ),
    ]
