# Generated by Django 5.0.1 on 2026-03-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingevent',
            name='event_type',
            field=models.CharField(choices=[('subscription.created', 'Suscripción creada'), ('subscription.updated', 'Suscripción actualizada'), ('subscription.canceled', 'Suscripción cancelada'), ('subscription.renewed', 'Suscripción renovada'), ('invoice.created', 'Factura creada'), ('invoice.paid', 'Factura pagada'), ('invoice.payment_failed', 'Pago fallido'), ('plan.upgraded', 'Plan mejorado'), ('plan.downgraded', 'Plan reducido'), ('usage.exceeded', 'Límite excedido'), ('trial.started', 'Trial iniciado'), ('trial.ended', 'Trial finalizado'), ('alert', 'Alerta de uso')], db_index=True, max_length=50, verbose_name='Tipo de evento'),
        ),
    ]
