# Generated by Django 5.0.1 on 2026-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_alter_billingevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="True para planes con pricing personalizado",
                verbose_name="Plan personalizado",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Explorador"),
                    ("basic", "Agricultor"),
                    ("pro", "Empresarial"),
                ],
                db_index=True,
                max_length=20,
                unique=True,
            ),
        ),
    ]
