# Generated by Django 5.0.1 on 2026-08-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_plan_is_custom_alter_plan_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('free', 'Explorador'), ('basic', 'Agricultor'), ('pro', 'Empresarial'), ('enterprise', 'Corporativo')], db_index=True, max_length=20, unique=True),
        ),
    ]
