# Generated by Django 5.0.1 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_plan_tier'),
        ('base_agrotech', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EosdaRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.IntegerField(blank=True, help_text='Parcela de origen (IntegerField, no FK: cross-schema)', null=True, verbose_name='ID de Parcela')),
                ('operation', models.CharField(blank=True, default='', max_length=50, verbose_name='Operación')),
                ('index_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Índice espectral')),
                ('date_requested', models.DateField(blank=True, null=True, verbose_name='Fecha solicitada')),
                ('source', models.CharField(choices=[('eosda', 'EOSDA API'), ('cache', 'Cache')], db_index=True, default='eosda', max_length=10, verbose_name='Origen')),
                ('cost_estimated', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo estimado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de registro')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eosda_request_logs', to='base_agrotech.client', verbose_name='Tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eosda_request_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de consumo EOSDA',
                'verbose_name_plural': 'Registros de consumo EOSDA',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['tenant', 'created_at'], name='billing_eos_tenant__defe1d_idx'),
                    models.Index(fields=['tenant', 'operation'], name='billing_eos_tenant__f28ea4_idx'),
                ],
            },
        ),
    ]
