# Generated by Django 5.0.1 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_eosdarequestlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="payment_gateway",
            field=models.CharField(
                choices=[
                    ("mercadopago", "MercadoPago"),
                    ("paddle", "Paddle"),
                    ("stripe", "Stripe"),
                    ("wompi", "Wompi"),
                    ("manual", "Manual"),
                ],
                default="mercadopago",
                help_text="Gateway usado para procesar pagos",
                max_length=50,
                verbose_name="Pasarela de pago",
            ),
        ),
    ]
