# Generated by Django 5.1.2 on 2026-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_alter_subscription_payment_gateway"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payment_source_id",
            field=models.CharField(
                blank=True,
                help_text="Fuente de pago tokenizada (Wompi) para cobros automáticos recurrentes (3RI)",
                max_length=200,
                null=True,
                verbose_name="ID de fuente de pago",
            ),
        ),
    ]
