# Configuración de Netlify para AgroTech Digital
# Optimizado para Leaflet + Esri World Imagery

git add netlify.toml
git commit -m "fix: Simplificar CSP para permitir todos los recursos externos (tiles, CDNs, etc.)"
git push origin main
  command = "echo 'Desplegando archivos estáticos'"

[build.environment]
  NODE_VERSION = "18"

# ========================================
# REDIRECTS
# ========================================

# Redirigir todas las peticiones de API a Railway
[[redirects]]
  from = "/api/*"
  to = "https://site-production-208b.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Manejo de 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# ========================================
# HEADERS DE SEGURIDAD
# ========================================

[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy MUY permisivo para desarrollo - permite todos los recursos externos
    Content-Security-Policy = '''
      default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'; 
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; 
      style-src 'self' 'unsafe-inline' https:; 
      img-src 'self' data: blob: https: http:; 
      connect-src 'self' https: http:; 
      worker-src 'self' blob:;
      child-src 'self' blob:;
      font-src 'self' data: https: http:;
      frame-src 'self' https:;
      media-src 'self' https: http: data: blob:;
    '''
    
    # CORS headers
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache por defecto
    Cache-Control = "public, max-age=3600, must-revalidate"

# Cache largo para JS (RUTAS CORREGIDAS - relativas a publish)
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache largo para CSS (RUTAS CORREGIDAS - relativas a publish)
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache largo para imágenes (RUTAS CORREGIDAS - relativas a publish)
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
