# Nixpacks configuration for Railway with GDAL support

[phases.setup]
aptPkgs = ["gdal-bin", "libgdal-dev", "gcc", "g++", "make"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate_schemas --shared && python manage.py migrate_schemas && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
