# Generated by Django 5.1.2 on 2025-05-28 20:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título del Puesto')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('contract_type', models.CharField(blank=True, choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('freelance', 'Freelance')], max_length=50, null=True, verbose_name='Tipo de Contrato')),
                ('work_schedule', models.JSONField(blank=True, null=True, verbose_name='Horario de Trabajo')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
                ('account_type', models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=50, null=True, verbose_name='Tipo de Cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_on', models.DateField(auto_now=True, verbose_name='Última Modificación')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('accountant', 'Contador')], default='employee', max_length=50, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reporta a')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electrónico')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('image', models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen de perfil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título del Puesto')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('contract_type', models.CharField(blank=True, choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('freelance', 'Freelance')], max_length=50, null=True, verbose_name='Tipo de Contrato')),
                ('work_schedule', models.JSONField(blank=True, null=True, verbose_name='Horario de Trabajo')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
                ('account_type', models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=50, null=True, verbose_name='Tipo de Cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_on', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_on', models.DateField(blank=True, editable=False, verbose_name='Última Modificación')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('accountant', 'Contador')], default='employee', max_length=50, verbose_name='Rol')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reports_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reporta a')),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
