# Generated by Django 5.1.2 on 2026-02-10 16:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("base_agrotech", "0002_initial"),
        ("users", "0002_add_tenant_to_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_email_ci",
                violation_error_message="Ya existe una cuenta con este correo electrónico.",
            ),
        ),
    ]
