# Generated by Django 5.0.1 on 2026-08-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_unique_email_case_insensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verificado'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de verificación'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de verificación'),
        ),
    ]
