# Generated by Django 5.1.2 on 2025-07-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop', '0001_initial'),
        ('inventario', '0008_historicalsupply_attachments_historicalsupply_image_and_more'),
        ('labores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallaborinput',
            name='labor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='labores.labor'),
        ),
        migrations.AddField(
            model_name='historicallaborinput',
            name='supply',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.supply', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='laborinput',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_insumos', to='crop.crop'),
        ),
        migrations.AddField(
            model_name='laborinput',
            name='labor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='labores.labor'),
        ),
        migrations.AddField(
            model_name='laborinput',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.supply', verbose_name='Insumo'),
        ),
    ]
