# Generated by Django 5.1.2 on 2026-02-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0002_initial"),
        ("parcels", "0007_add_crop_catalog_phenological_stage_crop_cycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del cultivo"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre cientifico",
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Familia botanica",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cereals", "Cereales"),
                            ("legumes", "Leguminosas"),
                            ("fruits", "Frutales"),
                            ("vegetables", "Hortalizas"),
                            ("industrial", "Industriales"),
                            ("forage", "Pastos y Forrajes"),
                            ("tubers", "Tuberculos"),
                            ("oilseeds", "Oleaginosas"),
                            ("other", "Otros"),
                        ],
                        default="cereals",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "cycle_days_min",
                    models.IntegerField(default=90, verbose_name="Ciclo minimo (dias)"),
                ),
                (
                    "cycle_days_max",
                    models.IntegerField(
                        default=150, verbose_name="Ciclo maximo (dias)"
                    ),
                ),
                (
                    "temp_min",
                    models.FloatField(
                        default=15.0, verbose_name="Temperatura minima optima (C)"
                    ),
                ),
                (
                    "temp_max",
                    models.FloatField(
                        default=35.0, verbose_name="Temperatura maxima optima (C)"
                    ),
                ),
                (
                    "rainfall_min",
                    models.FloatField(
                        default=500.0, verbose_name="Precipitacion minima anual (mm)"
                    ),
                ),
                (
                    "rainfall_max",
                    models.FloatField(
                        default=2000.0, verbose_name="Precipitacion maxima anual (mm)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cultivo (Catalogo)",
                "verbose_name_plural": "Cultivos (Catalogo)",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CropCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Variedad"
                    ),
                ),
                ("planting_date", models.DateField(verbose_name="Fecha de siembra")),
                (
                    "estimated_harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha estimada de cosecha"
                    ),
                ),
                (
                    "actual_harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha real de cosecha"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("active", "Activo"),
                            ("harvested", "Cosechado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "planting_density",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Densidad de siembra (plantas/ha)",
                    ),
                ),
                (
                    "seed_amount",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Cantidad de semilla (kg/ha)",
                    ),
                ),
                (
                    "expected_yield",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Rendimiento esperado (ton/ha)",
                    ),
                ),
                (
                    "actual_yield",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Rendimiento real (ton/ha)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycles",
                        to="crop.cropcatalog",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_cycles",
                        to="parcels.parcel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo de Cultivo",
                "verbose_name_plural": "Ciclos de Cultivo",
                "ordering": ["-planting_date"],
            },
        ),
        migrations.CreateModel(
            name="PhenologicalStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre de la etapa"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "day_start",
                    models.IntegerField(verbose_name="Dia inicio (desde siembra)"),
                ),
                (
                    "day_end",
                    models.IntegerField(verbose_name="Dia fin (desde siembra)"),
                ),
                (
                    "ndvi_min",
                    models.FloatField(default=0.0, verbose_name="NDVI minimo esperado"),
                ),
                (
                    "ndvi_max",
                    models.FloatField(default=1.0, verbose_name="NDVI maximo esperado"),
                ),
                (
                    "ndvi_optimal",
                    models.FloatField(default=0.5, verbose_name="NDVI optimo"),
                ),
                (
                    "ndmi_min",
                    models.FloatField(
                        default=-1.0, verbose_name="NDMI minimo esperado"
                    ),
                ),
                (
                    "ndmi_max",
                    models.FloatField(default=1.0, verbose_name="NDMI maximo esperado"),
                ),
                (
                    "ndmi_optimal",
                    models.FloatField(default=0.2, verbose_name="NDMI optimo"),
                ),
                (
                    "savi_min",
                    models.FloatField(default=0.0, verbose_name="SAVI minimo esperado"),
                ),
                (
                    "savi_max",
                    models.FloatField(default=1.0, verbose_name="SAVI maximo esperado"),
                ),
                (
                    "savi_optimal",
                    models.FloatField(default=0.4, verbose_name="SAVI optimo"),
                ),
                (
                    "water_need",
                    models.IntegerField(
                        default=3, verbose_name="Necesidad hidrica (1-5)"
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(default=False, verbose_name="Etapa critica"),
                ),
                (
                    "critical_alert",
                    models.TextField(
                        blank=True, null=True, verbose_name="Alerta en etapa critica"
                    ),
                ),
                (
                    "crop_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crop.cropcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa Fenologica",
                "verbose_name_plural": "Etapas Fenologicas",
                "ordering": ["crop_catalog", "order", "day_start"],
                "unique_together": {("crop_catalog", "order")},
            },
        ),
    ]
