# Generated by Django 5.0.1 on 2026-03-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_cropvariety_update_crop_variety_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcrop',
            name='variety',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crop.cropvariety', verbose_name='Variedad'),
        ),
    ]
