# Generated by Django 5.0.1 on 2026-06-07 19:16
#
# NOTA: Migración IDEMPOTENTE — otras ramas pudieron agregar tenant_id
# a los modelos de crop (rama cropassignment). Se usan columnas/índices
# con IF NOT EXISTS para no duplicar.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_alter_historicalcrop_variety'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='crop',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
                migrations.AddField(
                    model_name='cropcycle',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
                migrations.AddField(
                    model_name='croptype',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
                migrations.AddField(
                    model_name='cropvariety',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
                migrations.AddField(
                    model_name='historicalcrop',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "crop_crop" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "crop_crop_tenant_id_294c228c" ON "crop_crop" ("tenant_id"); '
                        'ALTER TABLE "crop_cropcycle" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "crop_cropcycle_tenant_id_aa4a0997" ON "crop_cropcycle" ("tenant_id"); '
                        'ALTER TABLE "crop_croptype" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "crop_croptype_tenant_id_980cb241" ON "crop_croptype" ("tenant_id"); '
                        'ALTER TABLE "crop_cropvariety" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "crop_cropvariety_tenant_id_7e5c9a8d" ON "crop_cropvariety" ("tenant_id"); '
                        'ALTER TABLE "crop_historicalcrop" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "crop_historicalcrop_tenant_id_c6723073" ON "crop_historicalcrop" ("tenant_id");'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
