# Generated by Django 5.0.1 on 2026-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_alter_historicalcrop_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
        ),
        migrations.AddField(
            model_name='historicalcrop',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
        ),
    ]
