# Generated by Django 5.1.2 on 2026-05-27 23:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0005_alter_historicalcrop_variety"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cropvariety",
            options={
                "ordering": ["crop_catalog", "crop_type", "name"],
                "verbose_name": "Variedad de cultivo",
                "verbose_name_plural": "Variedades de cultivo",
            },
        ),
        migrations.AlterUniqueTogether(
            name="cropvariety",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="altitud_max_msnm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Altitud máx (msnm)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="altitud_min_msnm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Altitud mín (msnm)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="altura_promedio_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Altura promedio (cm)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="calidad_grano",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Calidad de grano / fruto",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="casa_registradora",
            field=models.CharField(
                blank=True,
                max_length=160,
                null=True,
                verbose_name="Casa registradora / laboratorio",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="codigo_registro_ica",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name="Registro ICA / sello",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="crop_catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="varieties",
                to="crop.cropcatalog",
                verbose_name="Cultivo (catálogo)",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="densidad_siembra_kg_ha",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Densidad de siembra (kg/ha)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="dias_a_floracion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Días a floración"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="dias_a_maduracion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Días a maduración"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="distancia_surcos_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Distancia entre surcos (cm)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="fertilizacion_npk",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Fertilización NPK recomendada",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="fuente",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Fuente / Ficha técnica",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="lamina_riego_mm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Lámina de riego total (mm)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="pais_origen",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="País de origen"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="profundidad_siembra_cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Profundidad de siembra (cm)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="regiones_recomendadas",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Regiones recomendadas",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="rendimiento_conservador_t_ha",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Rendimiento conservador (t/ha)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="rendimiento_potencial_t_ha",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Rendimiento potencial (t/ha)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="rendimiento_promedio_t_ha",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Rendimiento promedio (t/ha)"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="resistencia_enfermedades",
            field=models.TextField(
                blank=True, null=True, verbose_name="Resistencia a enfermedades"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="resistencia_plagas",
            field=models.TextField(
                blank=True, null=True, verbose_name="Resistencia a plagas"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="riesgo_encamamiento",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Riesgo de encamamiento",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="tipo_variedad",
            field=models.CharField(
                choices=[
                    ("criolla", "Criolla"),
                    ("mejorada", "Mejorada"),
                    ("hibrida", "Híbrida"),
                    ("transgenica", "Transgénica"),
                    ("otra", "Otra"),
                ],
                default="mejorada",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="tipos_suelo",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Tipos de suelo ideales",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="tolerancia_salinidad",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Tolerancia a salinidad",
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="tolerancia_sequia",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Tolerancia a sequía"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="year_liberacion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Año de liberación"
            ),
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="crop_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="varieties",
                to="crop.croptype",
                verbose_name="Tipo de cultivo (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="cycle_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ciclo total (días, aprox.)"
            ),
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notas / Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre comercial"),
        ),
        migrations.AddConstraint(
            model_name="cropvariety",
            constraint=models.UniqueConstraint(
                condition=models.Q(("crop_catalog__isnull", False)),
                fields=("name", "crop_catalog"),
                name="unique_variety_per_catalog",
            ),
        ),
    ]
