# Generated by Django 5.1.2 on 2026-05-27 23:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_crop_assignments(apps, schema_editor):
    Crop = apps.get_model("crop", "Crop")
    CropAssignment = apps.get_model("crop", "CropAssignment")

    for crop in Crop.objects.exclude(parcel_id__isnull=True).iterator():
        exists = CropAssignment.objects.filter(crop_id=crop.id, is_active=True).exists()
        if not exists:
            CropAssignment.objects.create(
                crop_id=crop.id,
                parcel_id=crop.parcel_id,
                assigned_at=crop.sowing_date,
                is_active=True,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0006_alter_cropvariety_options_and_more"),
        ("parcels", "0008_parcelzonification_parcelzone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de asignacion"
                    ),
                ),
                (
                    "unassigned_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de desasignacion"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Asignacion activa"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="crop.crop",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_assignments",
                        to="parcels.parcel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignacion de cultivo",
                "verbose_name_plural": "Asignaciones de cultivo",
                "ordering": ["-is_active", "-assigned_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["crop", "is_active"],
                        name="crop_cropas_crop_id_448ad3_idx",
                    ),
                    models.Index(
                        fields=["parcel", "is_active"],
                        name="crop_cropas_parcel__4eec2d_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_crop_assignments, noop_reverse),
    ]
