# Generated by Django 5.1.2 on 2026-06-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0007_cropassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cropassignment",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="cropassignment",
            name="parcel",
        ),
        migrations.AlterModelOptions(
            name="cropvariety",
            options={
                "ordering": ["crop_type", "name"],
                "verbose_name": "Variedad de cultivo",
                "verbose_name_plural": "Variedades de cultivo",
            },
        ),
        migrations.RemoveConstraint(
            model_name="cropvariety",
            name="unique_variety_per_catalog",
        ),
        migrations.AlterUniqueTogether(
            name="cropvariety",
            unique_together={("name", "crop_type")},
        ),
        migrations.AddField(
            model_name="crop",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="cropcycle",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="croptype",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="cropvariety",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalcrop",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="crop_type",
            field=models.ForeignKey(
                default=16,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="varieties",
                to="crop.croptype",
                verbose_name="Tipo de cultivo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="cycle_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Días de ciclo (aprox.)"
            ),
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="cropvariety",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Nombre de la variedad"
            ),
        ),
        migrations.DeleteModel(
            name="CropAssignment",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="altitud_max_msnm",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="altitud_min_msnm",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="altura_promedio_cm",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="calidad_grano",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="casa_registradora",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="codigo_registro_ica",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="crop_catalog",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="densidad_siembra_kg_ha",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="dias_a_floracion",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="dias_a_maduracion",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="distancia_surcos_cm",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="fertilizacion_npk",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="fuente",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="lamina_riego_mm",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="pais_origen",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="profundidad_siembra_cm",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="regiones_recomendadas",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="rendimiento_conservador_t_ha",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="rendimiento_potencial_t_ha",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="rendimiento_promedio_t_ha",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="resistencia_enfermedades",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="resistencia_plagas",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="riesgo_encamamiento",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="tipo_variedad",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="tipos_suelo",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="tolerancia_salinidad",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="tolerancia_sequia",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="year_liberacion",
        ),
    ]
