# Generated by Django 5.0.1 on 2026-08-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_crop_tenant_id_cropcycle_tenant_id_and_more'),
        ('crop', '0008_remove_cropassignment_crop_and_more'),
    ]

    operations = [
    ]
