# Generated by Django 5.0.1 on 2026-08-09 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crop", "0009_merge_20260806_2258"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laborinput",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="laborinput",
            name="labor",
        ),
        migrations.RemoveField(
            model_name="laborinput",
            name="supply",
        ),
        migrations.DeleteModel(
            name="HistoricalLaborInput",
        ),
        migrations.DeleteModel(
            name="LaborInput",
        ),
    ]
