# Generated by Django 5.1.2 on 2025-05-28 20:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRHH', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del campo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del campo')),
                ('field_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de campo')),
                ('state', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado del campo')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Área geográfica del campo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('unique_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='ID Único')),
                ('soil_type', models.CharField(help_text='Especifica si es arenoso, arcillozo, etc', max_length=20, verbose_name='Tipo de suelo')),
                ('topography', models.CharField(help_text='Indica si es plano, inclinido, etc', max_length=20, verbose_name='Topografìa')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RRHH.employee', verbose_name='Responsable del campo')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='ParcelActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales de la acción', null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parcels.parcel')),
            ],
            options={
                'verbose_name': 'Log de acción de parcela',
                'verbose_name_plural': 'Logs de acciones de parcelas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
