# Generated by Django 5.1.2 on 2025-05-28 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelactionlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Opcional. Apunta al usuario real del sistema para auditoría multiusuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
