# Generated by Django 5.1.2 on 2025-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='geom',
            field=models.JSONField(blank=True, help_text='GeoJSON Polygon. Compatible con EOSDA API Connect.', null=True, verbose_name='GeoJSON del campo'),
        ),
    ]
