# Generated by Django 5.1.2 on 2025-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_parcel_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='eosda_id',
            field=models.CharField(blank=True, help_text='ID del campo en EOSDA', max_length=32, null=True, unique=True, verbose_name='ID EOSDA'),
        ),
    ]
