# Generated by Django 5.1.2 on 2025-08-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_eosda_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelSceneCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(max_length=64, verbose_name='ID de escena EOSDA')),
                ('date', models.DateField(verbose_name='Fecha de la escena')),
                ('index_type', models.CharField(choices=[('NDVI', 'NDVI'), ('NDMI', 'NDMI')], max_length=10, verbose_name='Tipo de índice')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos de la escena')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la imagen/capa WMTS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta completa de EOSDA')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_caches', to='parcels.parcel')),
            ],
            options={
                'verbose_name': 'Cache de escena satelital',
                'verbose_name_plural': 'Cache de escenas satelitales',
                'indexes': [models.Index(fields=['parcel', 'scene_id', 'index_type'], name='parcels_par_parcel__4dba21_idx')],
                'unique_together': {('parcel', 'scene_id', 'index_type')},
            },
        ),
    ]
