# Generated by Django 5.0.1 on 2025-12-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_parcelscenecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaUsoEOSDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, db_index=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('requests_desde_cache', models.IntegerField(default=0)),
                ('requests_a_api', models.IntegerField(default=0)),
                ('tiempo_promedio_ms', models.IntegerField(default=0, help_text='Tiempo promedio en milisegundos')),
                ('errores', models.IntegerField(default=0)),
                ('tipo_operacion', models.CharField(choices=[('statistics', 'Statistics API'), ('field_mgmt', 'Field Management API'), ('scenes', 'Scene Search')], max_length=50)),
                ('indice', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Estadística EOSDA',
                'verbose_name_plural': 'Estadísticas EOSDA',
                'db_table': 'estadistica_uso_eosda',
                'indexes': [models.Index(fields=['fecha', 'tipo_operacion'], name='estadistica_fecha_033b83_idx')],
                'unique_together': {('fecha', 'tipo_operacion', 'indice')},
            },
        ),
        migrations.CreateModel(
            name='CacheDatosEOSDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Hash SHA-256 de geometría + fechas + índice', max_length=64, unique=True)),
                ('geometria', models.JSONField(help_text='GeoJSON de la parcela')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('indice', models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('NDMI', 'Normalized Difference Moisture Index'), ('SAVI', 'Soil Adjusted Vegetation Index'), ('EVI', 'Enhanced Vegetation Index')], max_length=10)),
                ('datos_satelitales', models.JSONField(help_text='Datos EOSDA completos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(db_index=True)),
                ('hits', models.IntegerField(default=0, help_text='Número de veces consultado')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cache_eosda', to='parcels.parcel')),
            ],
            options={
                'verbose_name': 'Caché EOSDA',
                'verbose_name_plural': 'Cachés EOSDA',
                'db_table': 'cache_datos_eosda',
                'indexes': [models.Index(fields=['cache_key', 'fecha_expiracion'], name='cache_datos_cache_k_87c60d_idx'), models.Index(fields=['parcela', 'indice'], name='cache_datos_parcela_b8ec72_idx')],
            },
        ),
    ]
