# Generated by Django 5.1.2 on 2026-02-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0006_estadisticausoeosda_cachedatoseosda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cachedatoseosda",
            name="parcela",
        ),
        migrations.DeleteModel(
            name="EstadisticaUsoEOSDA",
        ),
        migrations.DeleteModel(
            name="CacheDatosEOSDA",
        ),
    ]
