# Generated by Django 5.1.2 on 2026-05-27 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0007_add_crop_catalog_phenological_stage_crop_cycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelZonification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene_date",
                    models.DateField(verbose_name="Fecha de la escena base"),
                ),
                (
                    "index_base",
                    models.CharField(
                        default="ndvi",
                        help_text="Indice satelital usado para clusterizar (ndvi, ndmi, savi, ndre)",
                        max_length=10,
                        verbose_name="Indice base",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("kmeans", "K-means"),
                            ("isodata", "ISODATA"),
                            ("jenks", "Jenks (natural breaks)"),
                            ("percentiles", "Percentiles fijos"),
                            ("manual", "Manual"),
                        ],
                        default="kmeans",
                        max_length=20,
                    ),
                ),
                (
                    "k_zones",
                    models.IntegerField(default=5, verbose_name="Numero de zonas (k)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("ready", "Lista"),
                            ("failed", "Fallo"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_pixels", models.IntegerField(default=0)),
                (
                    "pixel_resolution_m",
                    models.FloatField(
                        default=10.0, verbose_name="Resolucion del pixel (m)"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonifications",
                        to="parcels.parcel",
                        verbose_name="Parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zonificacion de parcela",
                "verbose_name_plural": "Zonificaciones de parcela",
                "ordering": ["-scene_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParcelZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_id",
                    models.IntegerField(verbose_name="ID de cluster (k-means)"),
                ),
                ("label", models.CharField(max_length=40, verbose_name="Etiqueta")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("low", "Bajo vigor"),
                            ("mid_low", "Vigor medio-bajo"),
                            ("mid", "Vigor medio"),
                            ("mid_high", "Vigor medio-alto"),
                            ("high", "Alto vigor"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                ("pixel_count", models.IntegerField(default=0)),
                ("area_ha", models.FloatField(default=0.0)),
                ("ndvi_mean", models.FloatField(blank=True, null=True)),
                ("ndvi_std", models.FloatField(blank=True, null=True)),
                ("ndvi_min", models.FloatField(blank=True, null=True)),
                ("ndvi_max", models.FloatField(blank=True, null=True)),
                ("ndmi_mean", models.FloatField(blank=True, null=True)),
                ("ndmi_std", models.FloatField(blank=True, null=True)),
                ("savi_mean", models.FloatField(blank=True, null=True)),
                ("savi_std", models.FloatField(blank=True, null=True)),
                ("ndre_mean", models.FloatField(blank=True, null=True)),
                ("ndre_std", models.FloatField(blank=True, null=True)),
                (
                    "geometry_geojson",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Poligono GeoJSON"
                    ),
                ),
                ("recomendacion", models.TextField(blank=True, null=True)),
                (
                    "zonification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="parcels.parcelzonification",
                        verbose_name="Zonificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona de manejo",
                "verbose_name_plural": "Zonas de manejo",
                "ordering": ["zonification", "cluster_id"],
            },
        ),
        migrations.AddIndex(
            model_name="parcelzonification",
            index=models.Index(
                fields=["parcel", "-scene_date"], name="parcels_par_parcel__6307dd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parcelzone",
            unique_together={("zonification", "cluster_id")},
        ),
    ]
