# Generated by Django 5.1.2 on 2026-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_add_crop_catalog_phenological_stage_crop_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheDatosEOSDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, help_text='Client.id del tenant propietario de este cache', verbose_name='ID del Tenant')),
                ('parcela_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Parcela')),
                ('indice', models.CharField(max_length=10, verbose_name='Indice espectral')),
                ('tipo_dato', models.CharField(max_length=50, verbose_name='Tipo de dato')),
                ('geometria_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash SHA-256 de geometria')),
                ('datos', models.JSONField(verbose_name='Datos cacheados')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creacion')),
                ('expira_en', models.DateTimeField(db_index=True, verbose_name='Fecha de expiracion')),
            ],
            options={
                'verbose_name': 'Cache de datos EOSDA',
                'verbose_name_plural': 'Cache de datos EOSDA',
                'indexes': [models.Index(fields=['tenant_id', 'indice'], name='parcels_cac_tenant__12a5c9_idx'), models.Index(fields=['tenant_id', 'geometria_hash'], name='parcels_cac_tenant__a60987_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaUsoEOSDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, help_text='Client.id del tenant que realizo la solicitud', verbose_name='ID del Tenant')),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint llamado')),
                ('tipo_request', models.CharField(max_length=50, verbose_name='Tipo de request')),
                ('exitoso', models.BooleanField(default=True, verbose_name='Fue exitoso?')),
                ('desde_cache', models.BooleanField(default=False, verbose_name='Provino de cache?')),
                ('codigo_estado', models.IntegerField(blank=True, null=True, verbose_name='Codigo HTTP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del request')),
            ],
            options={
                'verbose_name': 'Estadistica de uso EOSDA',
                'verbose_name_plural': 'Estadisticas de uso EOSDA',
                'indexes': [models.Index(fields=['tenant_id', 'timestamp'], name='parcels_est_tenant__d6a476_idx'), models.Index(fields=['tenant_id', 'exitoso'], name='parcels_est_tenant__c894b9_idx')],
            },
        ),
    ]
