# Generated by Django 5.1.2 on 2026-06-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_parcelzonification_parcelzone_and_more'),
        ('parcels', '0008_tenant_scoping_cache_eosda'),
    ]

    operations = [
    ]
