# Generated by Django 5.0.1 on 2026-06-07 16:53
#
# NOTA: Esta migración es IDEMPOTENTE para soportar historiales divergentes:
# - Puede ejecutarse sobre una BD que ya tiene tenant_id/CropHealthStatus
#   (rama parcelzonification que aplicaba las mismas operaciones).
# - Las columnas/índices/tablas se crean con IF NOT EXISTS.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_tenant_scoping_cache_eosda'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='parcel',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
                migrations.AddField(
                    model_name='parcelactionlog',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
                migrations.AddField(
                    model_name='parcelscenecache',
                    name='tenant_id',
                    field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant'),
                ),
                migrations.CreateModel(
                    name='CropHealthStatus',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant')),
                        ('ndvi_last', models.FloatField(blank=True, null=True, verbose_name='Ultimo NDVI')),
                        ('ndmi_last', models.FloatField(blank=True, null=True, verbose_name='Ultimo NDMI')),
                        ('evi_last', models.FloatField(blank=True, null=True, verbose_name='Ultimo EVI')),
                        ('last_observation_date', models.DateTimeField(blank=True, null=True, verbose_name='Ultima observacion')),
                        ('last_image_date', models.DateField(blank=True, null=True, verbose_name='Fecha de la ultima imagen')),
                        ('observation_quality', models.CharField(choices=[('excellent', 'Excelente — Imagen reciente, baja nubosidad'), ('good', 'Buena — Imagen utilizable con algunas limitaciones'), ('limited', 'Limitada — Alta nubosidad, analisis parcial'), ('no_observation', 'Sin observacion confiable — No hay datos opticos validos')], default='no_observation', max_length=20, verbose_name='Calidad de observacion')),
                        ('confidence_score', models.IntegerField(default=0, verbose_name='Confianza del estado (0-100)')),
                        ('days_without_observation', models.IntegerField(default=0, verbose_name='Dias sin observacion')),
                        ('active_alerts', models.JSONField(blank=True, default=list, verbose_name='Alertas activas')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to='parcels.parcel', verbose_name='Parcela')),
                    ],
                    options={
                        'verbose_name': 'Estado de salud del cultivo',
                        'verbose_name_plural': 'Estados de salud de cultivos',
                        'indexes': [models.Index(fields=['tenant_id'], name='parcels_cro_tenant__be0208_idx'), models.Index(fields=['parcel', 'updated_at'], name='parcels_cro_parcel__44e86c_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "parcels_parcel" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "parcels_parcel_tenant_id_553f139b" ON "parcels_parcel" ("tenant_id"); '
                        'ALTER TABLE "parcels_parcelactionlog" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "parcels_parcelactionlog_tenant_id_2a617e50" ON "parcels_parcelactionlog" ("tenant_id"); '
                        'ALTER TABLE "parcels_parcelscenecache" ADD COLUMN IF NOT EXISTS "tenant_id" integer NULL; '
                        'CREATE INDEX IF NOT EXISTS "parcels_parcelscenecache_tenant_id_0530dca3" ON "parcels_parcelscenecache" ("tenant_id"); '
                        'CREATE TABLE IF NOT EXISTS "parcels_crophealthstatus" ('
                        '    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,'
                        '    "tenant_id" integer NULL,'
                        '    "ndvi_last" double precision NULL,'
                        '    "ndmi_last" double precision NULL,'
                        '    "evi_last" double precision NULL,'
                        '    "last_observation_date" timestamp with time zone NULL,'
                        '    "last_image_date" date NULL,'
                        '    "observation_quality" varchar(20) NOT NULL,'
                        '    "confidence_score" integer NOT NULL,'
                        '    "days_without_observation" integer NOT NULL,'
                        '    "active_alerts" jsonb NOT NULL,'
                        '    "created_at" timestamp with time zone NOT NULL,'
                        '    "updated_at" timestamp with time zone NOT NULL,'
                        '    "parcel_id" bigint NOT NULL UNIQUE REFERENCES "parcels_parcel" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED'
                        '); '
                        'CREATE INDEX IF NOT EXISTS "parcels_cro_tenant__be0208_idx" ON "parcels_crophealthstatus" ("tenant_id"); '
                        'CREATE INDEX IF NOT EXISTS "parcels_cro_parcel__44e86c_idx" ON "parcels_crophealthstatus" ("parcel_id", "updated_at");'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
