# Generated by Django 5.0.1 on 2026-06-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_crop_health_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Tenant')),
                ('event_type', models.CharField(choices=[('image_processed', 'Imagen procesada'), ('no_observation', 'Sin observacion'), ('weather_update', 'Actualizacion clima'), ('ndvi_change', 'Cambio en NDVI'), ('alert', 'Alerta'), ('system_check', 'Verificacion del sistema')], max_length=30, verbose_name='Tipo de evento')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del evento')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_events', to='parcels.parcel')),
            ],
            options={
                'verbose_name': 'Evento de monitoreo',
                'verbose_name_plural': 'Eventos de monitoreo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parcel', '-created_at'], name='parcels_mon_parcel__f24b01_idx'), models.Index(fields=['tenant_id', '-created_at'], name='parcels_mon_tenant__85322f_idx')],
            },
        ),
    ]
