# Generated by Django 5.1.2 on 2026-06-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0009_merge_20260616_1405"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcelzonification",
            name="parcel",
        ),
        migrations.AddField(
            model_name="parcel",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="parcelactionlog",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="parcelscenecache",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.CreateModel(
            name="CropHealthStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="ID del Tenant",
                    ),
                ),
                (
                    "ndvi_last",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ultimo NDVI"
                    ),
                ),
                (
                    "ndmi_last",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ultimo NDMI"
                    ),
                ),
                (
                    "evi_last",
                    models.FloatField(blank=True, null=True, verbose_name="Ultimo EVI"),
                ),
                (
                    "last_observation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultima observacion"
                    ),
                ),
                (
                    "last_image_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de la ultima imagen"
                    ),
                ),
                (
                    "observation_quality",
                    models.CharField(
                        choices=[
                            (
                                "excellent",
                                "Excelente — Imagen reciente, baja nubosidad",
                            ),
                            (
                                "good",
                                "Buena — Imagen utilizable con algunas limitaciones",
                            ),
                            ("limited", "Limitada — Alta nubosidad, analisis parcial"),
                            (
                                "no_observation",
                                "Sin observacion confiable — No hay datos opticos validos",
                            ),
                        ],
                        default="no_observation",
                        max_length=20,
                        verbose_name="Calidad de observacion",
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        default=0, verbose_name="Confianza del estado (0-100)"
                    ),
                ),
                (
                    "days_without_observation",
                    models.IntegerField(default=0, verbose_name="Dias sin observacion"),
                ),
                (
                    "active_alerts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Alertas activas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parcel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_status",
                        to="parcels.parcel",
                        verbose_name="Parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de salud del cultivo",
                "verbose_name_plural": "Estados de salud de cultivos",
            },
        ),
        migrations.DeleteModel(
            name="ParcelZone",
        ),
        migrations.DeleteModel(
            name="ParcelZonification",
        ),
        migrations.AddIndex(
            model_name="crophealthstatus",
            index=models.Index(
                fields=["tenant_id"], name="parcels_cro_tenant__be0208_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crophealthstatus",
            index=models.Index(
                fields=["parcel", "updated_at"], name="parcels_cro_parcel__44e86c_idx"
            ),
        ),
    ]
