# Generated by Django 5.1.2 on 2026-06-16 15:12
#
# NOTA: Esta migración originalmente también agregaba tenant_id a
# parcel/parcelactionlog/parcelscenecache y creaba CropHealthStatus.
# Esas operaciones quedaron duplicadas con '0009_crop_health_status'
# (cadena de tenant scoping). Se eliminaron aquí para evitar columnas
# duplicadas en bases nuevas; 0009_crop_health_status es idempotente.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0009_merge_20260616_1405"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcelzonification",
            name="parcel",
        ),
        migrations.DeleteModel(
            name="ParcelZone",
        ),
        migrations.DeleteModel(
            name="ParcelZonification",
        ),
    ]
