# Generated by Django 5.0.1 on 2026-08-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0010_monitoring_events'),
        ('parcels', '0011_parcelzonification_parcelzone'),
    ]

    operations = [
    ]
