# Generated by Django 5.0.1 on 2026-08-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcels", "0012_merge_20260806_2258"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcelzonification",
            name="parcel_id",
        ),
        migrations.AddField(
            model_name="parcelzonification",
            name="parcel",
            field=models.ForeignKey(
                db_column="parcel_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zonifications",
                to="parcels.parcel",
                verbose_name="Parcela",
            ),
        ),
    ]
