# Generated by Django 5.0.1 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0013_fix_zonification_parcel_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("local", "Solo local"),
                    ("syncing", "Sincronizando"),
                    ("synced", "Sincronizada"),
                    ("error", "Error de sincronización"),
                ],
                default="local",
                max_length=20,
                verbose_name="Estado de sincronización EOSDA",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sync_error",
            field=models.TextField(blank=True, null=True, verbose_name="Error de sincronización EOSDA"),
        ),
    ]
