# Generated by Django 5.1.2 on 2026-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0014_parcel_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcelzone",
            name="brecha_pct",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Brecha vs promedio del lote (%)"
            ),
        ),
        migrations.AddField(
            model_name="parcelzone",
            name="drainage_direction",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Dirección de drenaje",
            ),
        ),
        migrations.AddField(
            model_name="parcelzone",
            name="priority",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("media", "Media"),
                    ("alta", "Alta"),
                    ("critica", "Crítica"),
                ],
                default="media",
                max_length=20,
                verbose_name="Prioridad de intervención",
            ),
        ),
    ]
