# Generated by Django 5.1.2 on 2025-05-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRHH', '0001_initial'),
        ('base_agrotech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoremployee',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_agrotech.paymentmethod'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RRHH.department', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_agrotech.paymentmethod'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employee'),
        ),
    ]
