# Generated by Django 5.1.2 on 2026-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RRHH", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="contractoremployee",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractoremployee",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalposition",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicaltemporaryemployee",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
        migrations.AddField(
            model_name="temporaryemployee",
            name="tenant_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="ID del Tenant"
            ),
        ),
    ]
