"""
Comando para poblar el catalogo de cultivos con datos agronomicos verificados.
Incluye cultivos relevantes para Colombia y Latinoamerica con etapas fenologicas
y rangos optimos de indices satelitales (NDVI, NDMI, SAVI).

Fuentes:
    - FAO Crop Water Information
    - CIMMYT (Centro Internacional de Mejoramiento de Maiz y Trigo)
    - IRRI (International Rice Research Institute)
    - Cenicafe (Centro Nacional de Investigaciones de Cafe, Colombia)
    - CIAT (Centro Internacional de Agricultura Tropical)
    - Agrosavia (Corporacion Colombiana de Investigacion Agropecuaria)
    - CIP (Centro Internacional de la Papa)
    - Cenicana (Centro de Investigacion de la Cana de Azucar de Colombia)
    - Cenipalma (Centro de Investigacion en Palma de Aceite)

Uso:
    python manage.py populate_crop_catalog
    python manage.py populate_crop_catalog --tenant=finca_florez
"""

from django.core.management.base import BaseCommand
from crop.models import CropCatalog, PhenologicalStage
import logging

logger = logging.getLogger(__name__)


CROP_DATABASE = [
    {
        'name': 'Maiz',
        'scientific_name': 'Zea mays',
        'family': 'Poaceae',
        'category': 'cereals',
        'description': 'Cereal de gran importancia economica. Se adapta a diversos climas tropicales y subtropicales. Principal cereal de las Americas.',
        'cycle_days_min': 100,
        'cycle_days_max': 150,
        'temp_min': 18.0,
        'temp_max': 35.0,
        'rainfall_min': 500.0,
        'rainfall_max': 1200.0,
        'stages': [
            {
                'name': 'Germinacion y Emergencia',
                'order': 1,
                'day_start': 0,
                'day_end': 12,
                'ndvi_min': 0.10, 'ndvi_max': 0.25, 'ndvi_optimal': 0.18,
                'ndmi_min': 0.05, 'ndmi_max': 0.20, 'ndmi_optimal': 0.15,
                'savi_min': 0.05, 'savi_max': 0.20, 'savi_optimal': 0.12,
                'water_need': 3,
                'is_critical': False,
                'description': 'La semilla absorbe agua y emerge del suelo. Las raices primarias se establecen.',
            },
            {
                'name': 'Crecimiento Vegetativo (V1-V6)',
                'order': 2,
                'day_start': 13,
                'day_end': 35,
                'ndvi_min': 0.25, 'ndvi_max': 0.55, 'ndvi_optimal': 0.42,
                'ndmi_min': 0.10, 'ndmi_max': 0.30, 'ndmi_optimal': 0.22,
                'savi_min': 0.15, 'savi_max': 0.45, 'savi_optimal': 0.32,
                'water_need': 3,
                'is_critical': False,
                'description': 'Desarrollo rapido de hojas. La planta establece su sistema radicular.',
            },
            {
                'name': 'Desarrollo Vegetativo (V7-VT)',
                'order': 3,
                'day_start': 36,
                'day_end': 55,
                'ndvi_min': 0.55, 'ndvi_max': 0.80, 'ndvi_optimal': 0.70,
                'ndmi_min': 0.15, 'ndmi_max': 0.40, 'ndmi_optimal': 0.30,
                'savi_min': 0.40, 'savi_max': 0.70, 'savi_optimal': 0.55,
                'water_need': 4,
                'is_critical': False,
                'description': 'Maximo crecimiento de hojas y tallo. Se forma la espiga masculina.',
            },
            {
                'name': 'Floracion y Polinizacion',
                'order': 4,
                'day_start': 56,
                'day_end': 70,
                'ndvi_min': 0.75, 'ndvi_max': 0.92, 'ndvi_optimal': 0.85,
                'ndmi_min': 0.25, 'ndmi_max': 0.50, 'ndmi_optimal': 0.38,
                'savi_min': 0.60, 'savi_max': 0.85, 'savi_optimal': 0.72,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'ETAPA CRITICA: Un deficit hidrico de 4-8 dias durante floracion puede reducir el rendimiento entre 40% y 60%. Estres termico (>35C) afecta la polinizacion.',
                'description': 'La panoja libera polen y los estigmas lo capturan para fertilizar los granos.',
            },
            {
                'name': 'Llenado de Grano',
                'order': 5,
                'day_start': 71,
                'day_end': 100,
                'ndvi_min': 0.55, 'ndvi_max': 0.80, 'ndvi_optimal': 0.68,
                'ndmi_min': 0.15, 'ndmi_max': 0.35, 'ndmi_optimal': 0.25,
                'savi_min': 0.45, 'savi_max': 0.70, 'savi_optimal': 0.58,
                'water_need': 4,
                'is_critical': True,
                'critical_alert': 'Etapa critica para rendimiento final. Los granos acumulan almidon. Estres hidrico reduce peso del grano.',
                'description': 'Los granos se llenan con almidon y nutrientes. NDVI comienza a descender naturalmente.',
            },
            {
                'name': 'Maduracion Fisiologica',
                'order': 6,
                'day_start': 101,
                'day_end': 150,
                'ndvi_min': 0.20, 'ndvi_max': 0.55, 'ndvi_optimal': 0.38,
                'ndmi_min': -0.10, 'ndmi_max': 0.20, 'ndmi_optimal': 0.05,
                'savi_min': 0.15, 'savi_max': 0.45, 'savi_optimal': 0.28,
                'water_need': 2,
                'is_critical': False,
                'description': 'Las hojas se secan naturalmente. El grano pierde humedad hasta nivel de cosecha (~14%).',
            },
        ]
    },
    {
        'name': 'Arroz',
        'scientific_name': 'Oryza sativa',
        'family': 'Poaceae',
        'category': 'cereals',
        'description': 'Cereal semiacuatico. Requiere suelos inundados o alta humedad durante gran parte del ciclo. Base alimentaria de Colombia.',
        'cycle_days_min': 110,
        'cycle_days_max': 150,
        'temp_min': 20.0,
        'temp_max': 38.0,
        'rainfall_min': 1000.0,
        'rainfall_max': 2500.0,
        'stages': [
            {
                'name': 'Plantula y Establecimiento',
                'order': 1,
                'day_start': 0,
                'day_end': 20,
                'ndvi_min': 0.10, 'ndvi_max': 0.30, 'ndvi_optimal': 0.20,
                'ndmi_min': 0.20, 'ndmi_max': 0.50, 'ndmi_optimal': 0.40,
                'savi_min': 0.05, 'savi_max': 0.25, 'savi_optimal': 0.15,
                'water_need': 4,
                'is_critical': False,
                'description': 'Transplante o emergencia directa. El campo generalmente esta inundado.',
            },
            {
                'name': 'Macollamiento',
                'order': 2,
                'day_start': 21,
                'day_end': 50,
                'ndvi_min': 0.30, 'ndvi_max': 0.65, 'ndvi_optimal': 0.50,
                'ndmi_min': 0.25, 'ndmi_max': 0.55, 'ndmi_optimal': 0.42,
                'savi_min': 0.20, 'savi_max': 0.55, 'savi_optimal': 0.38,
                'water_need': 5,
                'is_critical': False,
                'description': 'La planta produce hijuelos (macollas). Determina la cantidad de paniculas.',
            },
            {
                'name': 'Elongacion y Paniculas',
                'order': 3,
                'day_start': 51,
                'day_end': 75,
                'ndvi_min': 0.65, 'ndvi_max': 0.88, 'ndvi_optimal': 0.78,
                'ndmi_min': 0.30, 'ndmi_max': 0.55, 'ndmi_optimal': 0.45,
                'savi_min': 0.50, 'savi_max': 0.80, 'savi_optimal': 0.65,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'Etapa de formacion de paniculas. Deficit hidrico puede reducir drasticamente el numero de granos por panicula.',
                'description': 'El tallo se alarga y se forman las paniculas dentro de la vaina.',
            },
            {
                'name': 'Floracion y Espigamiento',
                'order': 4,
                'day_start': 76,
                'day_end': 90,
                'ndvi_min': 0.75, 'ndvi_max': 0.92, 'ndvi_optimal': 0.85,
                'ndmi_min': 0.30, 'ndmi_max': 0.55, 'ndmi_optimal': 0.45,
                'savi_min': 0.60, 'savi_max': 0.85, 'savi_optimal': 0.72,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'ETAPA MAS CRITICA DEL ARROZ. Temperaturas >35C o estres hidrico causa esterilidad de espiguillas, reduciendo rendimiento hasta 70%.',
                'description': 'Las paniculas emergen y se produce la polinizacion. Maxima sensibilidad.',
            },
            {
                'name': 'Llenado de Grano',
                'order': 5,
                'day_start': 91,
                'day_end': 120,
                'ndvi_min': 0.50, 'ndvi_max': 0.78, 'ndvi_optimal': 0.65,
                'ndmi_min': 0.15, 'ndmi_max': 0.40, 'ndmi_optimal': 0.28,
                'savi_min': 0.40, 'savi_max': 0.68, 'savi_optimal': 0.55,
                'water_need': 3,
                'is_critical': False,
                'description': 'Los granos se llenan con almidon. Se retira gradualmente el agua del campo.',
            },
            {
                'name': 'Maduracion',
                'order': 6,
                'day_start': 121,
                'day_end': 150,
                'ndvi_min': 0.20, 'ndvi_max': 0.50, 'ndvi_optimal': 0.35,
                'ndmi_min': -0.10, 'ndmi_max': 0.20, 'ndmi_optimal': 0.05,
                'savi_min': 0.15, 'savi_max': 0.40, 'savi_optimal': 0.28,
                'water_need': 1,
                'is_critical': False,
                'description': 'Grano maduro, campo seco. Listo para cosecha cuando la humedad del grano es ~22%.',
            },
        ]
    },
    {
        'name': 'Cafe Arabica',
        'scientific_name': 'Coffea arabica',
        'family': 'Rubiaceae',
        'category': 'industrial',
        'description': 'Cultivo perenne de zonas tropicales de montana. Colombia es referente mundial en cafe arabica. Ciclo anual de produccion.',
        'cycle_days_min': 240,
        'cycle_days_max': 365,
        'temp_min': 15.0,
        'temp_max': 28.0,
        'rainfall_min': 1500.0,
        'rainfall_max': 2500.0,
        'stages': [
            {
                'name': 'Vegetativo',
                'order': 1,
                'day_start': 0,
                'day_end': 60,
                'ndvi_min': 0.55, 'ndvi_max': 0.80, 'ndvi_optimal': 0.70,
                'ndmi_min': 0.20, 'ndmi_max': 0.45, 'ndmi_optimal': 0.35,
                'savi_min': 0.40, 'savi_max': 0.70, 'savi_optimal': 0.55,
                'water_need': 3,
                'is_critical': False,
                'description': 'Crecimiento de ramas y hojas. La planta acumula energia para la floracion.',
            },
            {
                'name': 'Floracion',
                'order': 2,
                'day_start': 61,
                'day_end': 90,
                'ndvi_min': 0.60, 'ndvi_max': 0.82, 'ndvi_optimal': 0.72,
                'ndmi_min': 0.25, 'ndmi_max': 0.50, 'ndmi_optimal': 0.38,
                'savi_min': 0.45, 'savi_max': 0.72, 'savi_optimal': 0.58,
                'water_need': 4,
                'is_critical': True,
                'critical_alert': 'La floracion del cafe depende de un periodo seco seguido de lluvia. Estres hidrico prolongado reduce drasticamente el cuajado de frutos.',
                'description': 'Floracion inducida por lluvia despues de periodo seco. Las flores abren por 2-3 dias.',
            },
            {
                'name': 'Formacion de Fruto',
                'order': 3,
                'day_start': 91,
                'day_end': 180,
                'ndvi_min': 0.60, 'ndvi_max': 0.85, 'ndvi_optimal': 0.75,
                'ndmi_min': 0.25, 'ndmi_max': 0.50, 'ndmi_optimal': 0.40,
                'savi_min': 0.45, 'savi_max': 0.75, 'savi_optimal': 0.60,
                'water_need': 4,
                'is_critical': False,
                'description': 'El fruto (cereza) crece y se desarrolla. Periodo de alta demanda nutricional.',
            },
            {
                'name': 'Maduracion del Fruto',
                'order': 4,
                'day_start': 181,
                'day_end': 270,
                'ndvi_min': 0.55, 'ndvi_max': 0.78, 'ndvi_optimal': 0.68,
                'ndmi_min': 0.20, 'ndmi_max': 0.45, 'ndmi_optimal': 0.32,
                'savi_min': 0.40, 'savi_max': 0.68, 'savi_optimal': 0.55,
                'water_need': 3,
                'is_critical': True,
                'critical_alert': 'Periodo de maduracion critico. Exceso de lluvia puede causar caida de frutos y afectar calidad en taza.',
                'description': 'Las cerezas cambian de verde a rojo. Se realiza cosecha selectiva (picking).',
            },
            {
                'name': 'Cosecha y Recuperacion',
                'order': 5,
                'day_start': 271,
                'day_end': 365,
                'ndvi_min': 0.50, 'ndvi_max': 0.75, 'ndvi_optimal': 0.62,
                'ndmi_min': 0.15, 'ndmi_max': 0.40, 'ndmi_optimal': 0.28,
                'savi_min': 0.35, 'savi_max': 0.65, 'savi_optimal': 0.50,
                'water_need': 3,
                'is_critical': False,
                'description': 'Cosecha de cerezas maduras. La planta inicia recuperacion para el siguiente ciclo.',
            },
        ]
    },
    {
        'name': 'Soja',
        'scientific_name': 'Glycine max',
        'family': 'Fabaceae',
        'category': 'oilseeds',
        'description': 'Oleaginosa y leguminosa de alto valor proteico. Fija nitrogeno al suelo.',
        'cycle_days_min': 90,
        'cycle_days_max': 140,
        'temp_min': 20.0,
        'temp_max': 35.0,
        'rainfall_min': 450.0,
        'rainfall_max': 800.0,
        'stages': [
            {
                'name': 'Emergencia (VE-VC)',
                'order': 1,
                'day_start': 0,
                'day_end': 15,
                'ndvi_min': 0.10, 'ndvi_max': 0.28, 'ndvi_optimal': 0.20,
                'ndmi_min': 0.05, 'ndmi_max': 0.22, 'ndmi_optimal': 0.15,
                'savi_min': 0.05, 'savi_max': 0.22, 'savi_optimal': 0.14,
                'water_need': 3,
                'is_critical': False,
                'description': 'Emergencia de cotiledones y primera hoja unifoliada.',
            },
            {
                'name': 'Vegetativo (V1-V6)',
                'order': 2,
                'day_start': 16,
                'day_end': 40,
                'ndvi_min': 0.28, 'ndvi_max': 0.65, 'ndvi_optimal': 0.48,
                'ndmi_min': 0.10, 'ndmi_max': 0.35, 'ndmi_optimal': 0.25,
                'savi_min': 0.20, 'savi_max': 0.55, 'savi_optimal': 0.38,
                'water_need': 3,
                'is_critical': False,
                'description': 'Desarrollo de nudos y hojas trifoliadas. Fijacion de nitrogeno activa.',
            },
            {
                'name': 'Floracion (R1-R2)',
                'order': 3,
                'day_start': 41,
                'day_end': 60,
                'ndvi_min': 0.65, 'ndvi_max': 0.90, 'ndvi_optimal': 0.80,
                'ndmi_min': 0.20, 'ndmi_max': 0.45, 'ndmi_optimal': 0.35,
                'savi_min': 0.50, 'savi_max': 0.80, 'savi_optimal': 0.65,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'Floracion es etapa critica en soja. Deficit hidrico de 5 dias reduce significativamente el numero de vainas. Requiere buena disponibilidad de agua.',
                'description': 'Apertura de flores. Periodo de maxima sensibilidad al estres.',
            },
            {
                'name': 'Formacion de Vainas (R3-R4)',
                'order': 4,
                'day_start': 61,
                'day_end': 80,
                'ndvi_min': 0.70, 'ndvi_max': 0.92, 'ndvi_optimal': 0.82,
                'ndmi_min': 0.22, 'ndmi_max': 0.48, 'ndmi_optimal': 0.36,
                'savi_min': 0.55, 'savi_max': 0.82, 'savi_optimal': 0.68,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'Formacion y llenado inicial de vainas. Deficit hidrico reduce tamano y numero de granos por vaina.',
                'description': 'Las vainas se forman y los granos comienzan a llenar.',
            },
            {
                'name': 'Llenado de Grano (R5-R6)',
                'order': 5,
                'day_start': 81,
                'day_end': 110,
                'ndvi_min': 0.50, 'ndvi_max': 0.78, 'ndvi_optimal': 0.65,
                'ndmi_min': 0.12, 'ndmi_max': 0.35, 'ndmi_optimal': 0.25,
                'savi_min': 0.38, 'savi_max': 0.68, 'savi_optimal': 0.55,
                'water_need': 3,
                'is_critical': False,
                'description': 'Granos alcanzan tamano maximo. Hojas comienzan a amarillear.',
            },
            {
                'name': 'Maduracion (R7-R8)',
                'order': 6,
                'day_start': 111,
                'day_end': 140,
                'ndvi_min': 0.15, 'ndvi_max': 0.45, 'ndvi_optimal': 0.30,
                'ndmi_min': -0.10, 'ndmi_max': 0.15, 'ndmi_optimal': 0.02,
                'savi_min': 0.10, 'savi_max': 0.38, 'savi_optimal': 0.22,
                'water_need': 1,
                'is_critical': False,
                'description': 'Defoliacion natural. Granos secos, listos para cosecha (~13% humedad).',
            },
        ]
    },
    {
        'name': 'Cana de Azucar',
        'scientific_name': 'Saccharum officinarum',
        'family': 'Poaceae',
        'category': 'industrial',
        'description': 'Cultivo semi-perenne de alta produccion de biomasa. Valle del Cauca es la principal zona canera de Colombia.',
        'cycle_days_min': 300,
        'cycle_days_max': 420,
        'temp_min': 20.0,
        'temp_max': 38.0,
        'rainfall_min': 1200.0,
        'rainfall_max': 2000.0,
        'stages': [
            {
                'name': 'Brotacion y Establecimiento',
                'order': 1,
                'day_start': 0,
                'day_end': 40,
                'ndvi_min': 0.10, 'ndvi_max': 0.30, 'ndvi_optimal': 0.22,
                'ndmi_min': 0.10, 'ndmi_max': 0.30, 'ndmi_optimal': 0.22,
                'savi_min': 0.08, 'savi_max': 0.25, 'savi_optimal': 0.18,
                'water_need': 4,
                'is_critical': False,
                'description': 'Brotacion de yemas. La cana necesita humedad para establecimiento radicular.',
            },
            {
                'name': 'Macollamiento',
                'order': 2,
                'day_start': 41,
                'day_end': 120,
                'ndvi_min': 0.30, 'ndvi_max': 0.70, 'ndvi_optimal': 0.52,
                'ndmi_min': 0.15, 'ndmi_max': 0.42, 'ndmi_optimal': 0.30,
                'savi_min': 0.22, 'savi_max': 0.60, 'savi_optimal': 0.42,
                'water_need': 4,
                'is_critical': False,
                'description': 'Produccion de hijuelos. Define el numero de tallos por cepa.',
            },
            {
                'name': 'Gran Crecimiento',
                'order': 3,
                'day_start': 121,
                'day_end': 270,
                'ndvi_min': 0.70, 'ndvi_max': 0.92, 'ndvi_optimal': 0.82,
                'ndmi_min': 0.25, 'ndmi_max': 0.55, 'ndmi_optimal': 0.42,
                'savi_min': 0.55, 'savi_max': 0.85, 'savi_optimal': 0.70,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'Fase de mayor crecimiento y acumulacion de biomasa. Deficit hidrico en esta fase reduce drasticamente el tonelaje de cana por hectarea.',
                'description': 'Rapida elongacion de tallos. Maxima demanda de agua y nutrientes.',
            },
            {
                'name': 'Maduracion y Concentracion de Azucar',
                'order': 4,
                'day_start': 271,
                'day_end': 420,
                'ndvi_min': 0.45, 'ndvi_max': 0.75, 'ndvi_optimal': 0.60,
                'ndmi_min': 0.05, 'ndmi_max': 0.30, 'ndmi_optimal': 0.18,
                'savi_min': 0.35, 'savi_max': 0.65, 'savi_optimal': 0.50,
                'water_need': 2,
                'is_critical': True,
                'critical_alert': 'Fase de concentracion de sacarosa. Un estres hidrico moderado favorece la maduracion, pero el exceso de lluvia reduce la concentracion de azucar.',
                'description': 'El tallo acumula sacarosa. Se reduce el riego para inducir maduracion.',
            },
        ]
    },
    {
        'name': 'Sorgo',
        'scientific_name': 'Sorghum bicolor',
        'family': 'Poaceae',
        'category': 'cereals',
        'description': 'Cereal tolerante a la sequia. Alternativa al maiz en zonas secas de Colombia.',
        'cycle_days_min': 90,
        'cycle_days_max': 130,
        'temp_min': 20.0,
        'temp_max': 40.0,
        'rainfall_min': 400.0,
        'rainfall_max': 800.0,
        'stages': [
            {
                'name': 'Emergencia',
                'order': 1,
                'day_start': 0,
                'day_end': 10,
                'ndvi_min': 0.10, 'ndvi_max': 0.22, 'ndvi_optimal': 0.16,
                'ndmi_min': 0.05, 'ndmi_max': 0.18, 'ndmi_optimal': 0.12,
                'savi_min': 0.05, 'savi_max': 0.18, 'savi_optimal': 0.12,
                'water_need': 3,
                'is_critical': False,
                'description': 'Emergencia de plantulas. Tolerante a suelos secos.',
            },
            {
                'name': 'Crecimiento Vegetativo',
                'order': 2,
                'day_start': 11,
                'day_end': 40,
                'ndvi_min': 0.22, 'ndvi_max': 0.60, 'ndvi_optimal': 0.45,
                'ndmi_min': 0.08, 'ndmi_max': 0.30, 'ndmi_optimal': 0.20,
                'savi_min': 0.15, 'savi_max': 0.50, 'savi_optimal': 0.35,
                'water_need': 3,
                'is_critical': False,
                'description': 'Desarrollo de hojas y sistema radicular profundo.',
            },
            {
                'name': 'Floracion',
                'order': 3,
                'day_start': 41,
                'day_end': 65,
                'ndvi_min': 0.60, 'ndvi_max': 0.88, 'ndvi_optimal': 0.78,
                'ndmi_min': 0.18, 'ndmi_max': 0.42, 'ndmi_optimal': 0.32,
                'savi_min': 0.45, 'savi_max': 0.78, 'savi_optimal': 0.62,
                'water_need': 4,
                'is_critical': True,
                'critical_alert': 'Floracion del sorgo: etapa de mayor sensibilidad al deficit hidrico. Afecta directamente el numero de granos por panicula.',
                'description': 'Emergencia de la panicula y polinizacion.',
            },
            {
                'name': 'Llenado y Maduracion',
                'order': 4,
                'day_start': 66,
                'day_end': 130,
                'ndvi_min': 0.30, 'ndvi_max': 0.65, 'ndvi_optimal': 0.48,
                'ndmi_min': 0.05, 'ndmi_max': 0.28, 'ndmi_optimal': 0.15,
                'savi_min': 0.22, 'savi_max': 0.55, 'savi_optimal': 0.40,
                'water_need': 2,
                'is_critical': False,
                'description': 'Llenado de grano y secado natural. Cosecha a ~14% humedad.',
            },
        ]
    },
    {
        'name': 'Papa',
        'scientific_name': 'Solanum tuberosum',
        'family': 'Solanaceae',
        'category': 'tubers',
        'description': 'Tuberculo de clima frio. Boyaca, Cundinamarca y Narino son las principales zonas paperas de Colombia.',
        'cycle_days_min': 90,
        'cycle_days_max': 150,
        'temp_min': 10.0,
        'temp_max': 22.0,
        'rainfall_min': 600.0,
        'rainfall_max': 1200.0,
        'stages': [
            {
                'name': 'Brotacion y Emergencia',
                'order': 1,
                'day_start': 0,
                'day_end': 20,
                'ndvi_min': 0.10, 'ndvi_max': 0.28, 'ndvi_optimal': 0.20,
                'ndmi_min': 0.08, 'ndmi_max': 0.25, 'ndmi_optimal': 0.18,
                'savi_min': 0.08, 'savi_max': 0.22, 'savi_optimal': 0.16,
                'water_need': 3,
                'is_critical': False,
                'description': 'Los tuberculos-semilla brotan y las plantas emergen del suelo.',
            },
            {
                'name': 'Crecimiento Vegetativo',
                'order': 2,
                'day_start': 21,
                'day_end': 45,
                'ndvi_min': 0.30, 'ndvi_max': 0.65, 'ndvi_optimal': 0.50,
                'ndmi_min': 0.15, 'ndmi_max': 0.38, 'ndmi_optimal': 0.28,
                'savi_min': 0.22, 'savi_max': 0.55, 'savi_optimal': 0.40,
                'water_need': 4,
                'is_critical': False,
                'description': 'Desarrollo rapido del follaje. Primer aporque.',
            },
            {
                'name': 'Tuberizacion',
                'order': 3,
                'day_start': 46,
                'day_end': 75,
                'ndvi_min': 0.65, 'ndvi_max': 0.90, 'ndvi_optimal': 0.80,
                'ndmi_min': 0.22, 'ndmi_max': 0.48, 'ndmi_optimal': 0.38,
                'savi_min': 0.50, 'savi_max': 0.80, 'savi_optimal': 0.65,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'ETAPA CRITICA: Formacion de tuberculos. Deficit hidrico reduce drasticamente el numero y tamano de tuberculos. Mantener humedad constante.',
                'description': 'Los estolones engrosan formando nuevos tuberculos. Maxima demanda de agua.',
            },
            {
                'name': 'Llenado de Tuberculos',
                'order': 4,
                'day_start': 76,
                'day_end': 110,
                'ndvi_min': 0.55, 'ndvi_max': 0.82, 'ndvi_optimal': 0.70,
                'ndmi_min': 0.18, 'ndmi_max': 0.42, 'ndmi_optimal': 0.30,
                'savi_min': 0.42, 'savi_max': 0.72, 'savi_optimal': 0.58,
                'water_need': 4,
                'is_critical': False,
                'description': 'Los tuberculos crecen y acumulan almidon. El follaje se mantiene verde.',
            },
            {
                'name': 'Maduracion y Senescencia',
                'order': 5,
                'day_start': 111,
                'day_end': 150,
                'ndvi_min': 0.20, 'ndvi_max': 0.55, 'ndvi_optimal': 0.38,
                'ndmi_min': -0.05, 'ndmi_max': 0.22, 'ndmi_optimal': 0.08,
                'savi_min': 0.15, 'savi_max': 0.45, 'savi_optimal': 0.30,
                'water_need': 1,
                'is_critical': False,
                'description': 'El follaje se seca. Se suspende riego antes de cosecha para endurecer la piel del tuberculo.',
            },
        ]
    },
    {
        'name': 'Frijol',
        'scientific_name': 'Phaseolus vulgaris',
        'family': 'Fabaceae',
        'category': 'legumes',
        'description': 'Leguminosa de grano. Base de la dieta colombiana. Se cultiva en climas templados y frios.',
        'cycle_days_min': 75,
        'cycle_days_max': 120,
        'temp_min': 15.0,
        'temp_max': 28.0,
        'rainfall_min': 400.0,
        'rainfall_max': 800.0,
        'stages': [
            {
                'name': 'Germinacion y Emergencia',
                'order': 1,
                'day_start': 0,
                'day_end': 12,
                'ndvi_min': 0.10, 'ndvi_max': 0.25, 'ndvi_optimal': 0.18,
                'ndmi_min': 0.05, 'ndmi_max': 0.20, 'ndmi_optimal': 0.14,
                'savi_min': 0.05, 'savi_max': 0.20, 'savi_optimal': 0.12,
                'water_need': 3,
                'is_critical': False,
                'description': 'Emergencia de cotiledones.',
            },
            {
                'name': 'Vegetativo',
                'order': 2,
                'day_start': 13,
                'day_end': 35,
                'ndvi_min': 0.25, 'ndvi_max': 0.58, 'ndvi_optimal': 0.42,
                'ndmi_min': 0.10, 'ndmi_max': 0.32, 'ndmi_optimal': 0.22,
                'savi_min': 0.18, 'savi_max': 0.48, 'savi_optimal': 0.35,
                'water_need': 3,
                'is_critical': False,
                'description': 'Desarrollo de hojas trifoliadas y ramas.',
            },
            {
                'name': 'Floracion',
                'order': 3,
                'day_start': 36,
                'day_end': 50,
                'ndvi_min': 0.58, 'ndvi_max': 0.85, 'ndvi_optimal': 0.72,
                'ndmi_min': 0.18, 'ndmi_max': 0.42, 'ndmi_optimal': 0.32,
                'savi_min': 0.42, 'savi_max': 0.75, 'savi_optimal': 0.58,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'Floracion y cuajado de vainas. Deficit hidrico causa aborto de flores y vainas, reduciendo rendimiento hasta 50%.',
                'description': 'Apertura de flores. Periodo de alta sensibilidad a sequia.',
            },
            {
                'name': 'Llenado de Vainas',
                'order': 4,
                'day_start': 51,
                'day_end': 80,
                'ndvi_min': 0.50, 'ndvi_max': 0.78, 'ndvi_optimal': 0.65,
                'ndmi_min': 0.12, 'ndmi_max': 0.35, 'ndmi_optimal': 0.25,
                'savi_min': 0.38, 'savi_max': 0.68, 'savi_optimal': 0.55,
                'water_need': 3,
                'is_critical': False,
                'description': 'Los granos se llenan dentro de las vainas.',
            },
            {
                'name': 'Maduracion',
                'order': 5,
                'day_start': 81,
                'day_end': 120,
                'ndvi_min': 0.15, 'ndvi_max': 0.45, 'ndvi_optimal': 0.30,
                'ndmi_min': -0.10, 'ndmi_max': 0.15, 'ndmi_optimal': 0.02,
                'savi_min': 0.10, 'savi_max': 0.38, 'savi_optimal': 0.22,
                'water_need': 1,
                'is_critical': False,
                'description': 'Vainas y planta se secan. Cosecha manual o mecanica.',
            },
        ]
    },
    {
        'name': 'Pastura Brachiaria',
        'scientific_name': 'Brachiaria spp. (Urochloa)',
        'family': 'Poaceae',
        'category': 'forage',
        'description': 'Pasto tropical dominante en ganaderia colombiana. Alta produccion de biomasa y tolerancia a suelos acidos.',
        'cycle_days_min': 25,
        'cycle_days_max': 45,
        'temp_min': 20.0,
        'temp_max': 38.0,
        'rainfall_min': 800.0,
        'rainfall_max': 3000.0,
        'stages': [
            {
                'name': 'Rebrote post-pastoreo',
                'order': 1,
                'day_start': 0,
                'day_end': 7,
                'ndvi_min': 0.20, 'ndvi_max': 0.40, 'ndvi_optimal': 0.30,
                'ndmi_min': 0.08, 'ndmi_max': 0.25, 'ndmi_optimal': 0.18,
                'savi_min': 0.15, 'savi_max': 0.32, 'savi_optimal': 0.25,
                'water_need': 4,
                'is_critical': False,
                'description': 'Inicio del rebrote despues del pastoreo o corte.',
            },
            {
                'name': 'Crecimiento Activo',
                'order': 2,
                'day_start': 8,
                'day_end': 25,
                'ndvi_min': 0.40, 'ndvi_max': 0.75, 'ndvi_optimal': 0.60,
                'ndmi_min': 0.15, 'ndmi_max': 0.40, 'ndmi_optimal': 0.30,
                'savi_min': 0.30, 'savi_max': 0.65, 'savi_optimal': 0.48,
                'water_need': 4,
                'is_critical': False,
                'description': 'Fase de rapido crecimiento. Maxima calidad nutricional.',
            },
            {
                'name': 'Optimo para Pastoreo',
                'order': 3,
                'day_start': 26,
                'day_end': 35,
                'ndvi_min': 0.60, 'ndvi_max': 0.85, 'ndvi_optimal': 0.72,
                'ndmi_min': 0.20, 'ndmi_max': 0.45, 'ndmi_optimal': 0.35,
                'savi_min': 0.45, 'savi_max': 0.75, 'savi_optimal': 0.60,
                'water_need': 3,
                'is_critical': True,
                'critical_alert': 'Punto optimo para pastoreo o corte. Retrasar el ingreso de animales causa perdida de calidad nutricional y lignificacion del pasto.',
                'description': 'Maximo equilibrio entre cantidad y calidad. Momento ideal de pastoreo.',
            },
            {
                'name': 'Sobre-maduracion',
                'order': 4,
                'day_start': 36,
                'day_end': 45,
                'ndvi_min': 0.55, 'ndvi_max': 0.78, 'ndvi_optimal': 0.65,
                'ndmi_min': 0.12, 'ndmi_max': 0.35, 'ndmi_optimal': 0.25,
                'savi_min': 0.40, 'savi_max': 0.68, 'savi_optimal': 0.55,
                'water_need': 2,
                'is_critical': False,
                'description': 'El pasto pierde calidad nutricional. Tallos se lignifican. Menor digestibilidad.',
            },
        ]
    },
    {
        'name': 'Pastura Kikuyo',
        'scientific_name': 'Cenchrus clandestinus',
        'family': 'Poaceae',
        'category': 'forage',
        'description': 'Pasto de clima frio para ganaderia de leche. Dominante en altiplano cundiboyacense y Antioquia.',
        'cycle_days_min': 35,
        'cycle_days_max': 55,
        'temp_min': 10.0,
        'temp_max': 22.0,
        'rainfall_min': 800.0,
        'rainfall_max': 2000.0,
        'stages': [
            {
                'name': 'Rebrote',
                'order': 1,
                'day_start': 0,
                'day_end': 10,
                'ndvi_min': 0.25, 'ndvi_max': 0.45, 'ndvi_optimal': 0.35,
                'ndmi_min': 0.10, 'ndmi_max': 0.30, 'ndmi_optimal': 0.22,
                'savi_min': 0.18, 'savi_max': 0.38, 'savi_optimal': 0.28,
                'water_need': 4,
                'is_critical': False,
                'description': 'Rebrote despues de pastoreo. Crecimiento lento por temperaturas bajas.',
            },
            {
                'name': 'Crecimiento Activo',
                'order': 2,
                'day_start': 11,
                'day_end': 30,
                'ndvi_min': 0.45, 'ndvi_max': 0.78, 'ndvi_optimal': 0.65,
                'ndmi_min': 0.18, 'ndmi_max': 0.42, 'ndmi_optimal': 0.32,
                'savi_min': 0.32, 'savi_max': 0.68, 'savi_optimal': 0.52,
                'water_need': 4,
                'is_critical': False,
                'description': 'Fase de mayor crecimiento. Alta calidad para ganado lechero.',
            },
            {
                'name': 'Optimo para Pastoreo',
                'order': 3,
                'day_start': 31,
                'day_end': 42,
                'ndvi_min': 0.65, 'ndvi_max': 0.88, 'ndvi_optimal': 0.75,
                'ndmi_min': 0.22, 'ndmi_max': 0.48, 'ndmi_optimal': 0.38,
                'savi_min': 0.50, 'savi_max': 0.78, 'savi_optimal': 0.65,
                'water_need': 3,
                'is_critical': True,
                'critical_alert': 'Momento optimo de pastoreo. Altura ideal: 20-25cm. Retrasar causa acumulacion de material muerto y perdida de calidad.',
                'description': 'Maximo equilibrio nutritivo. Momento ideal de ingreso de ganado.',
            },
            {
                'name': 'Sobre-maduracion',
                'order': 4,
                'day_start': 43,
                'day_end': 55,
                'ndvi_min': 0.58, 'ndvi_max': 0.80, 'ndvi_optimal': 0.68,
                'ndmi_min': 0.15, 'ndmi_max': 0.38, 'ndmi_optimal': 0.28,
                'savi_min': 0.42, 'savi_max': 0.70, 'savi_optimal': 0.58,
                'water_need': 2,
                'is_critical': False,
                'description': 'Perdida de calidad. Acumulacion de fibra indigestible.',
            },
        ]
    },
    {
        'name': 'Palma de Aceite',
        'scientific_name': 'Elaeis guineensis',
        'family': 'Arecaceae',
        'category': 'industrial',
        'description': 'Cultivo perenne de alto rendimiento en aceite. Colombia es el primer productor de America Latina.',
        'cycle_days_min': 365,
        'cycle_days_max': 365,
        'temp_min': 22.0,
        'temp_max': 35.0,
        'rainfall_min': 1800.0,
        'rainfall_max': 3000.0,
        'stages': [
            {
                'name': 'Desarrollo Vegetativo',
                'order': 1,
                'day_start': 0,
                'day_end': 90,
                'ndvi_min': 0.55, 'ndvi_max': 0.82, 'ndvi_optimal': 0.70,
                'ndmi_min': 0.20, 'ndmi_max': 0.48, 'ndmi_optimal': 0.35,
                'savi_min': 0.40, 'savi_max': 0.72, 'savi_optimal': 0.58,
                'water_need': 4,
                'is_critical': False,
                'description': 'Emision de hojas nuevas. La palma adulta emite 20-24 hojas/ano.',
            },
            {
                'name': 'Floracion y Polinizacion',
                'order': 2,
                'day_start': 91,
                'day_end': 150,
                'ndvi_min': 0.60, 'ndvi_max': 0.85, 'ndvi_optimal': 0.74,
                'ndmi_min': 0.22, 'ndmi_max': 0.50, 'ndmi_optimal': 0.38,
                'savi_min': 0.45, 'savi_max': 0.75, 'savi_optimal': 0.62,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'Deficit hidrico durante floracion causa aborto de racimos, afectando la produccion 6-12 meses despues.',
                'description': 'Inflorescencias masculinas y femeninas se abren. Polinizacion por insectos.',
            },
            {
                'name': 'Desarrollo de Racimos',
                'order': 3,
                'day_start': 151,
                'day_end': 300,
                'ndvi_min': 0.60, 'ndvi_max': 0.85, 'ndvi_optimal': 0.75,
                'ndmi_min': 0.22, 'ndmi_max': 0.50, 'ndmi_optimal': 0.38,
                'savi_min': 0.45, 'savi_max': 0.78, 'savi_optimal': 0.62,
                'water_need': 4,
                'is_critical': False,
                'description': 'Los racimos crecen y los frutos acumulan aceite. Periodo de 5-6 meses.',
            },
            {
                'name': 'Maduracion y Cosecha',
                'order': 4,
                'day_start': 301,
                'day_end': 365,
                'ndvi_min': 0.55, 'ndvi_max': 0.80, 'ndvi_optimal': 0.70,
                'ndmi_min': 0.18, 'ndmi_max': 0.45, 'ndmi_optimal': 0.32,
                'savi_min': 0.40, 'savi_max': 0.70, 'savi_optimal': 0.58,
                'water_need': 3,
                'is_critical': False,
                'description': 'Los frutos maduran y cambian de color. Cosecha cada 10-15 dias durante todo el ano.',
            },
        ]
    },
    {
        'name': 'Algodon',
        'scientific_name': 'Gossypium hirsutum',
        'family': 'Malvaceae',
        'category': 'industrial',
        'description': 'Fibra textil. Se cultiva en Cordoba, Cesar y Tolima. Requiere clima calido y seco en cosecha.',
        'cycle_days_min': 140,
        'cycle_days_max': 180,
        'temp_min': 22.0,
        'temp_max': 38.0,
        'rainfall_min': 500.0,
        'rainfall_max': 1000.0,
        'stages': [
            {
                'name': 'Emergencia y Plantula',
                'order': 1,
                'day_start': 0,
                'day_end': 20,
                'ndvi_min': 0.10, 'ndvi_max': 0.28, 'ndvi_optimal': 0.20,
                'ndmi_min': 0.05, 'ndmi_max': 0.22, 'ndmi_optimal': 0.15,
                'savi_min': 0.08, 'savi_max': 0.22, 'savi_optimal': 0.16,
                'water_need': 3,
                'is_critical': False,
                'description': 'Emergencia de cotiledones y primeras hojas verdaderas.',
            },
            {
                'name': 'Crecimiento Vegetativo',
                'order': 2,
                'day_start': 21,
                'day_end': 55,
                'ndvi_min': 0.28, 'ndvi_max': 0.65, 'ndvi_optimal': 0.48,
                'ndmi_min': 0.10, 'ndmi_max': 0.35, 'ndmi_optimal': 0.25,
                'savi_min': 0.20, 'savi_max': 0.55, 'savi_optimal': 0.40,
                'water_need': 3,
                'is_critical': False,
                'description': 'Desarrollo de ramas fructiferas y vegetativas.',
            },
            {
                'name': 'Floracion y Fructificacion',
                'order': 3,
                'day_start': 56,
                'day_end': 100,
                'ndvi_min': 0.65, 'ndvi_max': 0.88, 'ndvi_optimal': 0.78,
                'ndmi_min': 0.20, 'ndmi_max': 0.45, 'ndmi_optimal': 0.35,
                'savi_min': 0.50, 'savi_max': 0.78, 'savi_optimal': 0.65,
                'water_need': 5,
                'is_critical': True,
                'critical_alert': 'Periodo de floracion y formacion de bellotas. Deficit hidrico causa caida de bellotas y reduce calidad de fibra.',
                'description': 'Flores se abren y se forman las bellotas (capsulas). Maxima demanda hidrica.',
            },
            {
                'name': 'Apertura de Bellotas',
                'order': 4,
                'day_start': 101,
                'day_end': 140,
                'ndvi_min': 0.40, 'ndvi_max': 0.68, 'ndvi_optimal': 0.55,
                'ndmi_min': 0.05, 'ndmi_max': 0.28, 'ndmi_optimal': 0.15,
                'savi_min': 0.30, 'savi_max': 0.58, 'savi_optimal': 0.45,
                'water_need': 2,
                'is_critical': False,
                'description': 'Las bellotas se abren exponiendo la fibra. Clima seco favorece calidad.',
            },
            {
                'name': 'Cosecha',
                'order': 5,
                'day_start': 141,
                'day_end': 180,
                'ndvi_min': 0.15, 'ndvi_max': 0.42, 'ndvi_optimal': 0.28,
                'ndmi_min': -0.10, 'ndmi_max': 0.15, 'ndmi_optimal': 0.02,
                'savi_min': 0.10, 'savi_max': 0.35, 'savi_optimal': 0.22,
                'water_need': 1,
                'is_critical': False,
                'description': 'Planta seca. Se aplican defoliantes antes de cosecha mecanica.',
            },
        ]
    },
]


class Command(BaseCommand):
    help = 'Poblar el catalogo de cultivos con datos agronomicos verificados'

    def add_arguments(self, parser):
        parser.add_argument(
            '--force',
            action='store_true',
            help='Forzar recreacion de cultivos existentes (elimina y recrea)',
        )

    def handle(self, *args, **options):
        force = options.get('force', False)
        created_crops = 0
        created_stages = 0
        skipped = 0

        for crop_data in CROP_DATABASE:
            stages_data = crop_data.pop('stages')

            existing = CropCatalog.objects.filter(name=crop_data['name']).first()
            if existing:
                if force:
                    self.stdout.write(f'  Recreando: {crop_data["name"]}')
                    existing.stages.all().delete()
                    existing.delete()
                else:
                    self.stdout.write(f'  Ya existe: {crop_data["name"]} (use --force para recrear)')
                    skipped += 1
                    continue

            catalog = CropCatalog.objects.create(**crop_data)
            created_crops += 1
            self.stdout.write(f'  + Creado: {catalog.name}')

            for stage_data in stages_data:
                PhenologicalStage.objects.create(
                    crop_catalog=catalog,
                    **stage_data
                )
                created_stages += 1

        self.stdout.write(self.style.SUCCESS(
            f'\nResultado: {created_crops} cultivos creados, '
            f'{created_stages} etapas fenologicas, '
            f'{skipped} omitidos (ya existian)'
        ))
