# Generated by Django 5.1.2 on 2026-06-22 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crop", "0008_remove_cropassignment_crop_and_more"),
        ("parcels", "0010_remove_parcelzonification_parcel_parcel_tenant_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaOperativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("humedad", "Estrés hídrico / humedad"),
                            ("vigor", "Vigor vegetativo"),
                            ("cobertura", "Cobertura vegetal"),
                            ("anomalia", "Anomalía / desviación"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("info", "Informativa"),
                            ("warning", "Advertencia"),
                            ("critical", "Crítica"),
                        ],
                        default="warning",
                        max_length=20,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "indice_afectado",
                    models.CharField(
                        choices=[
                            ("ndvi", "NDVI"),
                            ("ndmi", "NDMI"),
                            ("savi", "SAVI"),
                            ("evi", "EVI"),
                            ("ndre", "NDRE"),
                        ],
                        max_length=10,
                        verbose_name="Índice afectado",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Resumen en una línea para listas y notificaciones.",
                        max_length=200,
                        verbose_name="Título corto",
                    ),
                ),
                (
                    "zona",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción humana de la zona afectada (ej. 'Norte', 'A1-A4').",
                        max_length=100,
                        verbose_name="Zona del lote",
                    ),
                ),
                (
                    "causa_probable",
                    models.TextField(
                        help_text="Explicación agronómica del por qué del índice observado.",
                        verbose_name="Causa probable",
                    ),
                ),
                ("valor_observado", models.FloatField(verbose_name="Valor observado")),
                (
                    "valor_umbral_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Umbral mínimo esperado"
                    ),
                ),
                (
                    "valor_umbral_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Umbral máximo esperado"
                    ),
                ),
                (
                    "desviacion_pct",
                    models.FloatField(
                        blank=True,
                        help_text="% de desviación respecto al rango esperado de la etapa.",
                        null=True,
                        verbose_name="Desviación (%)",
                    ),
                ),
                (
                    "recomendacion",
                    models.TextField(
                        help_text="Acción concreta sugerida al productor.",
                        verbose_name="Recomendación",
                    ),
                ),
                (
                    "ventana_dias",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Días en los que conviene actuar.",
                        verbose_name="Ventana de acción (días)",
                    ),
                ),
                (
                    "fecha_escena_origen",
                    models.DateField(
                        help_text="Fecha de la imagen Sentinel-2 que originó la alerta.",
                        verbose_name="Fecha de la escena satelital",
                    ),
                ),
                (
                    "fecha_deteccion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Detectada en"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("atendida", "Atendida"),
                            ("posponer", "Pospuesta"),
                            ("descartada", "Descartada"),
                        ],
                        default="activa",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_estado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha cambio de estado"
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("util", "Útil — la situación era real"),
                            ("no_util", "No fue útil"),
                            ("falso_positivo", "Falso positivo"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Feedback",
                    ),
                ),
                (
                    "feedback_comentario",
                    models.TextField(
                        blank=True, default="", verbose_name="Comentario del feedback"
                    ),
                ),
                (
                    "fecha_feedback",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha del feedback"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Hash sha256 para evitar alertas duplicadas.",
                        max_length=64,
                        unique=True,
                        verbose_name="Huella única",
                    ),
                ),
                (
                    "contexto",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Etapa fenológica, cultivo, índices acompañantes, etc.",
                        verbose_name="Contexto agronómico",
                    ),
                ),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_atendidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendida por",
                    ),
                ),
                (
                    "crop_cycle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ciclo activo cuando se detectó la alerta (puede ser nulo).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_agronomicas",
                        to="crop.cropcycle",
                        verbose_name="Ciclo de cultivo",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas_agronomicas",
                        to="parcels.parcel",
                        verbose_name="Parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta agronómica",
                "verbose_name_plural": "Alertas agronómicas",
                "ordering": ["-fecha_deteccion"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("email", "Correo electrónico"),
                            ("in_app", "Dentro de la aplicación"),
                            ("webhook", "Webhook"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        help_text="Email, id de usuario o URL de webhook.",
                        max_length=255,
                        verbose_name="Destinatario",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviada", "Enviada"),
                            ("fallida", "Fallida"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "intentos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos"
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True, default="", verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "enviado_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado en"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "alerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="agronomic_alerts.alertaoperativa",
                        verbose_name="Alerta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación de alerta",
                "verbose_name_plural": "Notificaciones de alertas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="alertaoperativa",
            index=models.Index(
                fields=["parcel", "estado"], name="agronomic_a_parcel__8bed75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertaoperativa",
            index=models.Index(
                fields=["severidad", "estado"], name="agronomic_a_severid_649126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertaoperativa",
            index=models.Index(
                fields=["fecha_escena_origen"], name="agronomic_a_fecha_e_685688_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alertnotification",
            constraint=models.UniqueConstraint(
                fields=("alerta", "canal", "destinatario"),
                name="uq_notif_alerta_canal_destinatario",
            ),
        ),
    ]
